import { test,expect } from '@playwright/test';
import { execFileSync } from 'node:child_process';
import path from 'node:path';

test('E2E01/08/10: upload, review, generate, edit, approve, export, revise and export stale warning',async({page},testInfo)=>{
 test.setTimeout(240000);
 await page.goto('/projects');await page.getByRole('button',{name:'Create project',exact:true}).click();
 const create=page.getByRole('dialog');await create.getByLabel('Project name').fill(`Browser journey ${Date.now()}`);await create.getByLabel('Description').fill('Full persistent browser verification');await create.getByRole('button',{name:'Create project',exact:true}).click();
 await expect(page).toHaveURL(/\/projects\/[a-f0-9-]+$/);const projectId=page.url().split('/').at(-1)!;
 await page.getByRole('link',{name:'Upload requirements',exact:true}).click();await page.locator('input[type=file]').setInputFiles(path.resolve('fixtures/sample-login.pdf'));await page.getByRole('button',{name:'Extract requirements',exact:true}).click();
 await expect(page.getByRole('button',{name:'Confirm 10 requirements'})).toBeEnabled({timeout:60000});await page.getByRole('button',{name:'Confirm 10 requirements'}).click();await page.getByRole('link',{name:'Continue to generation'}).click();
 await page.getByRole('button',{name:'Generate test cases',exact:true}).click();await expect(page.getByRole('button',{name:'TC-001',exact:true})).toBeVisible({timeout:60000});
 await page.getByRole('button',{name:'TC-001',exact:true}).click();const editor=page.getByRole('dialog',{name:'Review test case'});await expect(editor).toBeVisible();await editor.getByLabel('Case title',{exact:true}).fill('Reviewer verified login boundary');await editor.getByRole('button',{name:'Save case changes'}).click();await expect(editor.getByText(/TC-001 · VERSION 2/)).toBeVisible();await editor.getByLabel('Decision note').fill('Verified against the source requirement.');await editor.getByRole('button',{name:'Approve case',exact:true}).click();await expect(editor.locator('.status-approved')).toBeVisible();await editor.getByRole('button',{name:'Close test case'}).click();
 await page.getByRole('link',{name:'Traceability',exact:true}).click();await expect(page.getByRole('heading',{name:'Requirement coverage'})).toBeVisible();
 async function exportWorkbook(label:string){await page.getByRole('button',{name:'Export XLSX',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Export test workbook'});await dialog.getByRole('radio',{name:/Approved only/}).check();await dialog.getByRole('button',{name:'Create export',exact:true}).click();await expect(dialog.getByRole('link',{name:'Download XLSX'})).toBeVisible({timeout:60000});const event=page.waitForEvent('download');await dialog.getByRole('link',{name:'Download XLSX'}).click();const download=await event;const target=testInfo.outputPath(`${label}.xlsx`);await download.saveAs(target);await dialog.getByRole('button',{name:'Close',exact:true}).click();return target;}
 function inspect(file:string){const python=process.env.PYTHON_BIN||(process.platform==='win32'?'.venv/Scripts/python.exe':'.venv/bin/python');return JSON.parse(execFileSync(python,['-c',"import openpyxl,json,sys; w=openpyxl.load_workbook(sys.argv[1]); print(json.dumps({'sheets':w.sheetnames,'cases':list(w['Test Cases'].values),'rtm':list(w['RTM'].values),'warnings':list(w['Warnings'].values)},default=str))",file],{encoding:'utf8',windowsHide:true}));}
 const workbook=inspect(await exportWorkbook('approved'));expect(workbook.sheets).toEqual(['Summary','Requirements','Scenarios','Test Cases','RTM','Warnings']);expect(workbook.cases).toHaveLength(2);expect(JSON.stringify(workbook.cases)).toContain('Reviewer verified login boundary');expect(JSON.stringify(workbook.warnings)).toMatch(/approved|uncovered/i);
 await page.goto(`/projects/${projectId}/requirements`);const row=page.locator('tr').filter({has:page.getByText('REQ-001',{exact:true})});await row.getByRole('button',{name:'Edit',exact:true}).click();const text=await row.getByLabel('Requirement text').inputValue();await row.getByLabel('Requirement text').fill(`${text} The account must be active.`);await row.getByRole('button',{name:'Save revision'}).click();await expect(row.getByText('Revision 2')).toBeVisible();
 await page.goto(`/projects/${projectId}/test-cases`);await expect(page.locator('tr').filter({has:page.getByRole('button',{name:'TC-001',exact:true})}).getByText('Stale',{exact:true})).toBeVisible();await page.reload();await expect(page.getByRole('button',{name:'Reviewer verified login boundary',exact:true})).toBeVisible();
 await page.goto(`/projects/${projectId}/traceability`);const staleWorkbook=inspect(await exportWorkbook('stale-approved'));expect(JSON.stringify(staleWorkbook.warnings)).toMatch(/stale/i);expect(staleWorkbook.cases).toHaveLength(2);
});

