import {describe,expect,it,vi} from 'vitest';
import {fetchRemoteRevision,resolveIntegrationSecret} from '../apps/web/lib/integration-providers';

const response=(body:unknown)=>new Response(JSON.stringify(body),{status:200,headers:{'content-type':'application/json'}});
describe('provider integration transports',()=>{
 it('reads an authoritative Confluence page revision without exposing its token',async()=>{const fetcher=vi.fn(async(_input:string|URL,_init?:RequestInit)=>response({id:'42',title:'Checkout requirements',version:{number:7},body:{storage:{value:'<p>Rules</p>'}},_links:{webui:'/wiki/spaces/REQ/pages/42'}}));const result=await fetchRemoteRevision({kind:'confluence',baseUrl:'https://acme.atlassian.net',projectKey:'REQ',credentialRef:'env://CONFLUENCE_TOKEN'},'42',{fetcher,env:{CONFLUENCE_TOKEN:'secret-token'}});expect(result.revision).toBe('7');expect(result.externalUrl).toContain('/wiki/spaces/REQ/pages/42');const [url,init]=fetcher.mock.calls[0];expect(String(url)).toContain('/wiki/api/v2/pages/42?body-format=storage');expect((init?.headers as Record<string,string>).authorization).toBe('Bearer secret-token');expect(JSON.stringify(result)).not.toContain('secret-token');});
 it('reads a Microsoft Graph drive item revision',async()=>{const fetcher=vi.fn(async(_input:string|URL,_init?:RequestInit)=>response({id:'item-9',name:'BRD.docx',eTag:'etag-4',webUrl:'https://contoso.sharepoint.com/BRD.docx'}));const result=await fetchRemoteRevision({kind:'sharepoint',baseUrl:'https://graph.microsoft.com',projectKey:'contoso.sharepoint.com,site-id,web-id',credentialRef:'env://GRAPH_TOKEN'},'item-9',{fetcher,env:{GRAPH_TOKEN:'graph-secret'}});expect(result.revision).toBe('etag-4');expect(String(fetcher.mock.calls[0][0])).toContain('/v1.0/sites/contoso.sharepoint.com%2Csite-id%2Cweb-id/drive/items/item-9');});
 it('reads bounded Figma node metadata with the provider token header',async()=>{const fetcher=vi.fn(async(_input:string|URL,_init?:RequestInit)=>response({name:'Design system',lastModified:'2026-09-29T10:00:00Z',version:'99',nodes:{'1:2':{document:{id:'1:2',name:'Checkout'}}}}));const result=await fetchRemoteRevision({kind:'figma',baseUrl:'https://api.figma.com',projectKey:'file-key',credentialRef:'env://FIGMA_TOKEN'},'1:2',{fetcher,env:{FIGMA_TOKEN:'figma-secret'}});expect(result.revision).toBe('99');expect(String(fetcher.mock.calls[0][0])).toContain('/v1/files/file-key/nodes?ids=1%3A2&depth=2');expect((fetcher.mock.calls[0][1]?.headers as Record<string,string>)['x-figma-token']).toBe('figma-secret');});
 it('blocks unapproved, insecure, and local destinations before network access',async()=>{const fetcher=vi.fn();for(const baseUrl of ['http://acme.atlassian.net','https://127.0.0.1','https://attacker.example'])await expect(fetchRemoteRevision({kind:'confluence',baseUrl,projectKey:'REQ',credentialRef:'env://TOKEN'},'42',{fetcher,env:{TOKEN:'secret'}})).rejects.toMatchObject({code:'INTEGRATION_CONFIGURATION_INVALID'});expect(fetcher).not.toHaveBeenCalled();});
 it('fails closed for missing and unconfigured secret references',()=>{expect(()=>resolveIntegrationSecret('env://MISSING',{})).toThrow(/not configured/);expect(()=>resolveIntegrationSecret('vault://testpilot/confluence',{})).toThrow(/resolver is not configured/);});
});
