import {describe,expect,it} from 'vitest';
import {analyzeBRD,MAX_SELF_HEALING_ATTEMPTS,renderAnalyzedDocument} from '../apps/web/lib/ai/self-healing-engine';

const input={title:'Claims Portal',projectType:'APPLICATION' as const,overview:'A portal for commercial insurance customers to submit and track claims.',users:'Claims handlers',inScope:'Claim intake',outOfScope:'Policy underwriting',capabilities:'submit a claim',businessRules:'Only active policies are eligible',integrations:'Corporate identity provider',assumptionsRisks:'Legacy claim identifiers remain stable',constraints:'WCAG 2.2 AA',acceptanceCriteria:'Accepted claims receive a reference number'};
const valid=JSON.stringify({completenessScore:92,ambiguityFlags:[],gherkinFeatures:[{title:'Submit a claim',featureText:'Feature: Submit a claim\n  Scenario: Valid claim\n    Given an active policy\n    When the customer submits a valid claim\n    Then a claim reference is displayed'}]});

describe('self-healing BRD analysis',()=>{
 it('re-prompts with exact validation feedback until strict output succeeds',async()=>{const prompts:string[]=[],outputs=['not json',JSON.stringify({completenessScore:140,ambiguityFlags:[],gherkinFeatures:[]}),valid];const result=await analyzeBRD(input,{mode:'external',callModel:async(prompt,attempt)=>{prompts.push(prompt);return outputs[attempt-1];}});expect(result.attempts).toBe(3);expect(result.analysis.completenessScore).toBe(92);expect(prompts[1]).toContain('Unexpected token');expect(prompts[2]).toContain('completenessScore');expect(prompts[2]).toContain('too_big');});
 it('fails closed after three malformed responses without exposing raw output',async()=>{let calls=0;await expect(analyzeBRD(input,{mode:'external',callModel:async()=>{calls++;return '{private malformed output';}})).rejects.toMatchObject({code:'AI_OUTPUT_INVALID',message:'The AI could not produce a valid requirement analysis after three attempts. Human review is required.'});expect(calls).toBe(MAX_SELF_HEALING_ATTEMPTS);});
 it('provides deterministic validated analysis without a paid model',async()=>{const result=await analyzeBRD({...input,overview:`${input.overview} It must be user-friendly.`},{mode:'fixture'});expect(result.analysis.completenessScore).toBeGreaterThan(0);expect(result.analysis.ambiguityFlags).toEqual(expect.arrayContaining([expect.objectContaining({term:'user-friendly'})]));expect(result.analysis.gherkinFeatures[0].featureText).toContain('Scenario:');expect(renderAnalyzedDocument(input,result.analysis)).toContain('## BDD features');});
});
