import {z} from 'zod';import {db} from './db';import {ApiError,membership} from './http';import {AGENTS,configInput,defaultContent,hash,lintAgentConfig} from './agent-config';
async function context(userId:string){const member=await db.membership.findFirst({where:{userId},include:{workspace:{include:{organization:true}}}});if(!member)throw new ApiError(403,'FORBIDDEN','Workspace access required.');return member}
export async function agentApi(req:Request,path:string[],userId:string):Promise<Response|undefined>{if(!['agent-configs','agent-runs','agent-findings','model-routes'].includes(path[0]))return;const ctx=await context(userId),url=new URL(req.url);
 if(path[0]==='agent-configs'&&path.length===1){if(req.method==='GET'){const projectId=url.searchParams.get('projectId');if(projectId)await membership(z.string().uuid().parse(projectId),userId);const rows=await db.agentConfigVersion.findMany({where:{OR:[{scope:'ORG',scopeKey:ctx.workspace.organizationId},...(projectId?[{scope:'PROJECT',scopeKey:projectId}]:[])]},orderBy:{createdAt:'desc'}});return Response.json({catalog:AGENTS.map(([key,name,family])=>({key,name,family,defaultContent:defaultContent(key)})),versions:rows});}if(!['ADMIN','QA_LEAD'].includes(ctx.role))throw new ApiError(403,'FORBIDDEN','Configuration editing requires administrator or QA lead access.');const body=configInput.parse(await req.json());if(body.scope==='ORG'&&body.scopeKey!==ctx.workspace.organizationId)throw new ApiError(403,'FORBIDDEN','Organization scope is invalid.');if(body.scope==='PROJECT')await membership(body.scopeKey,userId,['ADMIN','QA_LEAD']);const report=lintAgentConfig(body.content,body.agentKey);return Response.json(await db.agentConfigVersion.create({data:{...body,contentHash:hash(body.content),lintReport:report,createdBy:userId}}),{status:201});}
 if(path[0]==='agent-configs'&&path.length===2&&req.method==='PATCH'){if(!['ADMIN','QA_LEAD'].includes(ctx.role))throw new ApiError(403,'FORBIDDEN','Configuration governance requires administrator or QA lead access.');const item=await db.agentConfigVersion.findUnique({where:{id:z.string().uuid().parse(path[1])}});if(!item)throw new ApiError(404,'NOT_FOUND','Configuration version not found.');const {action}=z.object({action:z.enum(['LINT','SUBMIT','APPROVE','ACTIVATE','RETIRE'])}).strict().parse(await req.json());const report=lintAgentConfig(item.content,item.agentKey);if(!report.valid&&action!=='RETIRE')throw new ApiError(422,'CONFIG_INVALID','Resolve configuration lint errors before continuing.',report);const status=action==='LINT'?item.status:action==='SUBMIT'?'IN_REVIEW':action==='APPROVE'?'APPROVED':action==='ACTIVATE'?'ACTIVE':'RETIRED';if(action==='ACTIVATE'){if(item.status!=='APPROVED')throw new ApiError(409,'INVALID_STATE','Approve this version before activation.');await db.agentConfigVersion.updateMany({where:{scope:item.scope,scopeKey:item.scopeKey,agentKey:item.agentKey,status:'ACTIVE'},data:{status:'RETIRED'}});}return Response.json(await db.agentConfigVersion.update({where:{id:item.id},data:{status,lintReport:report,...(action==='APPROVE'?{approvedBy:userId}:{}),...(action==='ACTIVATE'?{activatedAt:new Date()}: {})}}));}
 if(path[0]==='model-routes'){
  if(req.method==='GET')return Response.json({routes:await db.agentModelRoute.findMany({where:{organizationId:ctx.workspace.organizationId},orderBy:{routeKey:'asc'}})});
  if(ctx.role!=='ADMIN')throw new ApiError(403,'FORBIDDEN','Only administrators can manage model routes.');
  const body=z.object({routeKey:z.string().regex(/^[a-z0-9-]+$/),displayName:z.string().min(2).max(80),provider:z.enum(['fixture','openai-compatible','azure-openai','anthropic']),model:z.string().min(1).max(120),baseUrl:z.string().url().or(z.literal('')),credentialRef:z.string().max(120).default(''),fallbackRouteKey:z.string().max(80).default(''),maxCostCents:z.number().int().min(0).max(100000),timeoutSeconds:z.number().int().min(10).max(600),enabled:z.boolean()}).strict().parse(await req.json());
  return Response.json(await db.agentModelRoute.upsert({where:{organizationId_routeKey:{organizationId:ctx.workspace.organizationId,routeKey:body.routeKey}},update:body,create:{...body,organizationId:ctx.workspace.organizationId,createdBy:userId}}));
 }
 if(path[0]==='agent-runs'&&req.method==='GET'){const runs=await db.agentRun.findMany({where:{project:{workspaceId:ctx.workspaceId}},orderBy:{startedAt:'desc'},take:100,include:{configVersion:{select:{version:true,scope:true}},_count:{select:{findings:true}},project:{select:{name:true}}}});return Response.json({runs});}
 if(path[0]==='agent-findings'&&req.method==='GET'){const findings=await db.agentFinding.findMany({where:{run:{project:{workspaceId:ctx.workspaceId}},...(url.searchParams.get('open')==='true'?{resolution:null}:{})},orderBy:{createdAt:'desc'},take:200,include:{run:{select:{agentKey:true,project:{select:{name:true}}}}}});return Response.json({findings});}
}
