import {db} from './db';
import {finishAgentRun,startAgentRun} from './agent-config';

type Finding={runId:string;targetType:string;targetId:string;severity:string;code:string;message:string;suggestedFix:string};

export async function verifyGeneratedStories(input:{projectId:string;organizationId:string;generatorRunId:string;storyIds:string[]}){
 const run=await startAgentRun({projectId:input.projectId,organizationId:input.organizationId,agentKey:'grounding-verifier',modelRoute:'deterministic-fixture',parentRunId:input.generatorRunId,inputRef:{storyIds:input.storyIds}});
 try{const stories=await db.userStory.findMany({where:{id:{in:input.storyIds},projectId:input.projectId},include:{requirementLinks:{include:{requirement:true}}}}),findings:Finding[]=[];
  for(const story of stories){const criteria=Array.isArray(story.acceptanceCriteria)?story.acceptanceCriteria.filter((v):v is string=>typeof v==='string'):[],source=story.requirementLinks.map(link=>link.requirement.text.toLowerCase()).join('\n');if(!story.requirementLinks.length)findings.push({runId:run.id,targetType:'USER_STORY',targetId:story.id,severity:'BLOCKER',code:'UNGROUNDED_STORY',message:'The generated story has no requirement evidence.',suggestedFix:'Link the story to a confirmed requirement.'});for(const criterion of criteria)if(!source.includes(criterion.toLowerCase()))findings.push({runId:run.id,targetType:'USER_STORY',targetId:story.id,severity:'WARNING',code:'UNSUPPORTED_ACCEPTANCE_CRITERION',message:`Acceptance criterion is not directly supported by linked requirement text: ${criterion}`,suggestedFix:'Rewrite the criterion from the cited requirement or mark the inference for review.'});}
  await db.$transaction([db.userStory.updateMany({where:{id:{in:input.storyIds}},data:{verifiedByRunId:run.id}}),...(findings.length?[db.agentFinding.createMany({data:findings})]:[])]);await finishAgentRun(run.id,{status:findings.length?'NEEDS_HUMAN':'SUCCEEDED',outputRef:{storyIds:input.storyIds},validation:{stories:stories.length,findings:findings.length}});return run.id;
 }catch(error){await finishAgentRun(run.id,{status:'FAILED',validation:{error:error instanceof Error?error.message:'Verification failed'}}).catch(()=>{});throw error;}
}

export async function verifyGeneratedTestDesign(input:{projectId:string;organizationId:string;generatorRunId:string;scenarioIds:string[];caseIds:string[];requestedTypes:string[]}){
 const grounding=await startAgentRun({projectId:input.projectId,organizationId:input.organizationId,agentKey:'grounding-verifier',modelRoute:'deterministic-fixture',parentRunId:input.generatorRunId,inputRef:{caseIds:input.caseIds}}),critic=await startAgentRun({projectId:input.projectId,organizationId:input.organizationId,agentKey:'test-design-critic',modelRoute:'deterministic-fixture',parentRunId:input.generatorRunId,inputRef:{scenarioIds:input.scenarioIds,caseIds:input.caseIds,requestedTypes:input.requestedTypes}});
 try{const [cases,citations]=await Promise.all([db.testCase.findMany({where:{id:{in:input.caseIds},projectId:input.projectId},include:{links:{include:{requirement:true}},steps:true}}),db.sourceCitation.findMany({where:{entityType:'test_case',entityId:{in:input.caseIds}}})]),groundingFindings:Finding[]=[],criticFindings:Finding[]=[];
  for(const item of cases){const evidence=citations.filter(citation=>citation.entityId===item.id);if(!evidence.length)groundingFindings.push({runId:grounding.id,targetType:'TEST_CASE',targetId:item.id,severity:'BLOCKER',code:'MISSING_CITATION',message:'Generated test case has no source citation.',suggestedFix:'Add a citation to the linked requirement source.'});for(const citation of evidence)if(citation.inferred)groundingFindings.push({runId:grounding.id,targetType:'TEST_CASE',targetId:item.id,severity:'WARNING',code:'INFERRED_EVIDENCE',message:'This case contains inferred evidence that requires reviewer confirmation.',suggestedFix:'Confirm the inference or replace it with a direct source quotation.'});if(!item.links.length||!item.steps.length||item.steps.some(step=>!step.action.trim()||!step.expectedResult.trim()))criticFindings.push({runId:critic.id,targetType:'TEST_CASE',targetId:item.id,severity:'BLOCKER',code:'INCOMPLETE_TEST_DESIGN',message:'The case is missing traceability or an executable action/expected-result pair.',suggestedFix:'Complete the steps and link at least one requirement.'});if(!input.requestedTypes.includes(item.type))criticFindings.push({runId:critic.id,targetType:'TEST_CASE',targetId:item.id,severity:'WARNING',code:'UNREQUESTED_CASE_TYPE',message:`Generated case type ${item.type} was not requested.`,suggestedFix:'Change the case type or regenerate with the intended design scope.'});}
  await db.$transaction([db.testCase.updateMany({where:{id:{in:input.caseIds}},data:{verifiedByRunId:critic.id}}),db.scenario.updateMany({where:{id:{in:input.scenarioIds}},data:{verifiedByRunId:critic.id}}),...(groundingFindings.length?[db.agentFinding.createMany({data:groundingFindings})]:[]),...(criticFindings.length?[db.agentFinding.createMany({data:criticFindings})]:[])]);await finishAgentRun(grounding.id,{status:groundingFindings.length?'NEEDS_HUMAN':'SUCCEEDED',outputRef:{caseIds:input.caseIds},validation:{cases:cases.length,findings:groundingFindings.length}});await finishAgentRun(critic.id,{status:criticFindings.length?'NEEDS_HUMAN':'SUCCEEDED',outputRef:{scenarioIds:input.scenarioIds,caseIds:input.caseIds},validation:{cases:cases.length,findings:criticFindings.length}});return {groundingRunId:grounding.id,criticRunId:critic.id};
 }catch(error){await Promise.all([finishAgentRun(grounding.id,{status:'FAILED',validation:{error:error instanceof Error?error.message:'Verification failed'}}).catch(()=>{}),finishAgentRun(critic.id,{status:'FAILED',validation:{error:error instanceof Error?error.message:'Verification failed'}}).catch(()=>{})]);throw error;}
}
