import {Document,HeadingLevel,Packer,Paragraph,TextRun} from 'docx';
import {z} from 'zod';
import {db} from './db';
import {ApiError,membership} from './http';
import {audit,ingestTextSource} from './ingestion';

const template=z.enum(['SIMPLE_PRD','BRD','SRS','AGILE_STORIES','API_REQUIREMENTS','DATA_MIGRATION','BLANK']);
const outlines:Record<z.infer<typeof template>,string>={
 SIMPLE_PRD:'# Product Requirements Document\n\n## Purpose\nDescribe the problem and intended outcome.\n\n## Users\n- Primary user:\n\n## Functional requirements\nFR-001. The system shall ...\n\n## Business rules\nBR-001. ...\n\n## Constraints and quality requirements\n- Security:\n- Accessibility:\n- Performance:\n\n## Acceptance criteria\nAC-001. Given ... when ... then ...',
 BRD:'# Business Requirements Document\n\n## Executive summary\n\n## Business objectives\n\n## Stakeholders and users\n\n## Scope\n### In scope\n### Out of scope\n\n## Business requirements\nBR-001. ...\n\n## Business rules\nRULE-001. ...\n\n## Assumptions and constraints\n\n## Acceptance criteria\nAC-001. ...',
 SRS:'# Software Requirements Specification\n\n## Purpose and scope\n\n## Product context\n\n## User classes\n\n## Functional requirements\nFR-001. The system shall ...\n\n## External interfaces\n\n## Data requirements\n\n## Non-functional requirements\n### Security\n### Accessibility\n### Performance\n### Reliability\n\n## Acceptance criteria\nAC-001. ...',
 AGILE_STORIES:'# Epic and User Stories\n\n## Product outcome\n\n## Epic 1\nAs a ... I want ... so that ...\n\n### Acceptance criteria\nAC-001. Given ... when ... then ...\n\n### Business rules\n\n### Dependencies and risks\n',
 API_REQUIREMENTS:'# API Requirements\n\n## Purpose and consumers\n\n## Authentication and authorization\n\n## Endpoints\nAPI-001. The API shall ...\n\n## Request and response rules\n\n## Validation and errors\n\n## Security, rate limits and audit\n\n## Acceptance criteria\nAC-001. ...',
 DATA_MIGRATION:'# Data Migration Requirements\n\n## Migration objective\n\n## Source and target systems\n\n## Data mapping and transformations\nMIG-001. ...\n\n## Validation and reconciliation\n\n## Security and retention\n\n## Cutover and rollback\n\n## Acceptance criteria\nAC-001. ...',
 BLANK:'# Requirements Document\n\nStart authoring here.'
};
const safeFilename=(title:string,extension:string)=>`${title.replace(/[^a-z0-9 _-]/gi,'').trim().replace(/\s+/g,'_').slice(0,80)||'Requirements'}.${extension}`;
function toDocx(content:string){const children=content.split(/\r?\n/).map(line=>{const heading=line.match(/^(#{1,3})\s+(.+)$/);if(heading)return new Paragraph({text:heading[2],heading:[HeadingLevel.TITLE,HeadingLevel.HEADING_1,HeadingLevel.HEADING_2][heading[1].length-1]});const bullet=line.match(/^[-*]\s+(.+)$/);if(bullet)return new Paragraph({text:bullet[1],bullet:{level:0}});return new Paragraph({children:[new TextRun(line)]});});return Packer.toBuffer(new Document({sections:[{properties:{},children}]}));}
async function ownedDocument(id:string,userId:string){z.uuid().parse(id);const document=await db.requirementDocument.findUnique({where:{id},include:{revisions:{orderBy:{version:'desc'},take:20}}});if(!document)throw new ApiError(404,'NOT_FOUND','Requirements document not found.');await membership(document.projectId,userId);return document;}
export async function authoringApi(req:Request,path:string[],userId:string):Promise<Response|undefined>{
 if(path[0]==='projects'&&path[1]&&path[2]==='authoring-documents'){
  const project=await membership(path[1],userId);
  if(path.length===3&&req.method==='GET')return Response.json({documents:await db.requirementDocument.findMany({where:{projectId:project.id},orderBy:{updatedAt:'desc'}})});
  if(path.length===3&&req.method==='POST'){const body=z.object({title:z.string().trim().min(3).max(120),templateType:template.default('SIMPLE_PRD')}).strict().parse(await req.json());const document=await db.$transaction(async tx=>{const created=await tx.requirementDocument.create({data:{projectId:project.id,title:body.title,templateType:body.templateType,content:outlines[body.templateType],createdBy:userId,updatedBy:userId}});await tx.requirementDocumentRevision.create({data:{documentId:created.id,version:1,title:created.title,content:created.content,createdBy:userId}});await audit(tx,project.id,userId,'requirement_document_created','RequirementDocument',created.id,undefined,{templateType:body.templateType});return created;});return Response.json(document,{status:201});}
 }
 if(path[0]!=='authoring-documents'||!path[1])return;
 const document=await ownedDocument(path[1],userId);
 if(path.length===2&&req.method==='GET')return Response.json(document);
 if(path.length===2&&req.method==='PATCH'){const body=z.object({title:z.string().trim().min(3).max(120),content:z.string().trim().min(20).max(100000),version:z.number().int().positive()}).strict().parse(await req.json());const updated=await db.$transaction(async tx=>{const result=await tx.requirementDocument.updateMany({where:{id:document.id,version:body.version},data:{title:body.title,content:body.content,status:'DRAFT',version:{increment:1},updatedBy:userId}});if(result.count!==1)throw new ApiError(409,'VERSION_CONFLICT','This document changed in another session. Reload before saving.',{current_version:document.version});const next=await tx.requirementDocument.findUniqueOrThrow({where:{id:document.id}});await tx.requirementDocumentRevision.create({data:{documentId:next.id,version:next.version,title:next.title,content:next.content,createdBy:userId}});await audit(tx,next.projectId,userId,'requirement_document_saved','RequirementDocument',next.id,{version:body.version},{version:next.version});return next;});return Response.json(updated);}
 if(path[2]==='download'&&req.method==='GET'){const format=z.enum(['md','docx']).default('docx').parse(new URL(req.url).searchParams.get('format')||'docx');const bytes=format==='docx'?await toDocx(document.content):Buffer.from(document.content,'utf8');return new Response(new Uint8Array(bytes),{headers:{'Content-Type':format==='docx'?'application/vnd.openxmlformats-officedocument.wordprocessingml.document':'text/markdown; charset=utf-8','Content-Disposition':`attachment; filename*=UTF-8''${encodeURIComponent(safeFilename(document.title,format))}`,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});}
 if(path[2]==='process'&&req.method==='POST'){if(document.status==='SUBMITTED')throw new ApiError(409,'ALREADY_SUBMITTED','This document version was already submitted. Edit and save it before extracting again.');if(document.content.length<20)throw new ApiError(422,'VALIDATION_ERROR','Add document content before extraction.');const result=await ingestTextSource(document.projectId,userId,document.content,safeFilename(document.title,'txt'));await db.$transaction(async tx=>{await tx.requirementDocument.update({where:{id:document.id},data:{status:'SUBMITTED',updatedBy:userId}});await audit(tx,document.projectId,userId,'requirement_document_submitted','RequirementDocument',document.id,undefined,{sourceId:result.source.id,version:document.version});});return Response.json(result,{status:202});}
}
