import { db } from './db';
import { ApiError } from './http';
import {z} from 'zod';

export async function enterpriseApi(req:Request,path:string[],userId:string):Promise<Response|undefined>{
 if(path[0]!=='enterprise')return;
 const membership=await db.membership.findFirst({where:{userId},include:{user:true,workspace:{include:{organization:{include:{integrations:true}},memberships:{include:{user:true}},projects:{select:{id:true,name:true}}}}}});
 if(!membership)throw new ApiError(403,'FORBIDDEN','Workspace access required.');
 if(path[1]==='members'){
  if(membership.role!=='ADMIN')throw new ApiError(403,'FORBIDDEN','Only workspace administrators can manage members.');
  if(req.method==='POST'){const body=z.object({email:z.string().email().transform(v=>v.toLowerCase()),name:z.string().trim().min(2).max(100),role:z.enum(['ADMIN','QA_LEAD','TESTER','VIEWER'])}).strict().parse(await req.json());const result=await db.$transaction(async tx=>{const user=await tx.user.upsert({where:{email:body.email},update:{name:body.name},create:{email:body.email,name:body.name}});const member=await tx.membership.upsert({where:{workspaceId_userId:{workspaceId:membership.workspaceId,userId:user.id}},update:{role:body.role},create:{workspaceId:membership.workspaceId,userId:user.id,role:body.role}});await tx.notification.create({data:{userId:user.id,kind:'WORKSPACE_ACCESS',title:'Workspace access granted',message:`You were added to ${membership.workspace.name} as ${body.role.replace('_',' ').toLowerCase()}.`,href:'/workspace'}});return member;});return Response.json(result,{status:201});}
  if(req.method==='PATCH'){const body=z.object({userId:z.string().uuid(),role:z.enum(['ADMIN','QA_LEAD','TESTER','VIEWER'])}).strict().parse(await req.json());if(body.userId===userId&&body.role!=='ADMIN')throw new ApiError(409,'SELF_DEMOTION_BLOCKED','Transfer administration before changing your own administrator role.');return Response.json(await db.membership.update({where:{workspaceId_userId:{workspaceId:membership.workspaceId,userId:body.userId}},data:{role:body.role}}));}
  if(req.method==='DELETE'){const target=z.string().uuid().parse(new URL(req.url).searchParams.get('userId'));if(target===userId)throw new ApiError(409,'SELF_REMOVAL_BLOCKED','Transfer administration before removing your own account.');await db.membership.delete({where:{workspaceId_userId:{workspaceId:membership.workspaceId,userId:target}}});return Response.json({deleted:true});}
 }
 if(req.method!=='GET')return;
 const projectIds=membership.workspace.projects.map(project=>project.id);
 const [sources,requirements,testCases,approvedCases,audit]=await Promise.all([
  db.sourceDocument.count({where:{projectId:{in:projectIds},deletedAt:null}}),db.requirement.count({where:{projectId:{in:projectIds},deletedAt:null}}),db.testCase.count({where:{projectId:{in:projectIds},deletedAt:null}}),db.testCase.count({where:{projectId:{in:projectIds},deletedAt:null,status:'approved'}}),db.auditEvent.findMany({where:{projectId:{in:projectIds}},orderBy:{createdAt:'desc'},take:100,include:{project:{select:{name:true}}}})
 ]);
 return Response.json({user:{id:membership.user.id,name:membership.user.name,email:membership.user.email,externalSubject:membership.user.externalSubject,createdAt:membership.user.createdAt},role:membership.role,workspace:{id:membership.workspace.id,name:membership.workspace.name,createdAt:membership.workspace.createdAt},organization:{id:membership.workspace.organization.id,name:membership.workspace.organization.name,slug:membership.workspace.organization.slug,ssoDomain:membership.workspace.organization.ssoDomain},members:membership.workspace.memberships.map(item=>({id:item.user.id,name:item.user.name,email:item.user.email,role:item.role,joinedAt:item.user.createdAt,active:item.user.active,provisioningSource:item.user.provisioningSource})),integrations:membership.workspace.organization.integrations.map(item=>({id:item.id,kind:item.kind,name:item.name,baseUrl:item.baseUrl,projectKey:item.projectKey,enabled:item.enabled,updatedAt:item.updatedAt})),capabilities:{scim:Boolean(process.env.SCIM_BEARER_TOKEN&&process.env.SCIM_WORKSPACE_ID),oidc:Boolean(process.env.OIDC_ISSUER&&process.env.OIDC_AUDIENCE&&process.env.OIDC_JWKS_URL),telemetry:Boolean(process.env.OTEL_EXPORTER_OTLP_ENDPOINT)},counts:{projects:projectIds.length,sources,requirements,testCases,approvedCases,members:membership.workspace.memberships.filter(item=>item.user.active).length},audit:audit.map(item=>({id:item.id,action:item.action,entityType:item.entityType,entityId:item.entityId,project:item.project.name,actorId:item.actorId,createdAt:item.createdAt}))});
}
