import {createHash} from 'node:crypto';
import {Prisma} from '@prisma/client';
import {z} from 'zod';
import {db} from './db';
import {ApiError,membership} from './http';
import {audit} from './ingestion';

type SnapshotItem={id:string;stableCode:string;text:string;revision:number};
type Change={stableCode:string;kind:'ADDED'|'MODIFIED'|'DELETED'|'UNCHANGED';before?:string;after?:string;affectedCaseIds:string[]};
const words=(value:string)=>new Set(value.toLowerCase().match(/[a-z0-9]+/g)||[]);
export function semanticSimilarity(a:string,b:string){const left=words(a),right=words(b);if(!left.size&&!right.size)return 1;const shared=[...left].filter(value=>right.has(value)).length;return shared/Math.max(1,new Set([...left,...right]).size);}
export function diffSnapshots(before:SnapshotItem[],after:SnapshotItem[],links:Map<string,string[]>=new Map()):Change[]{
 const oldByCode=new Map(before.map(item=>[item.stableCode,item])),newByCode=new Map(after.map(item=>[item.stableCode,item]));
 return [...new Set([...oldByCode.keys(),...newByCode.keys()])].sort().map(stableCode=>{const old=oldByCode.get(stableCode),next=newByCode.get(stableCode);let kind:Change['kind']='UNCHANGED';if(!old)kind='ADDED';else if(!next)kind='DELETED';else if(old.text!==next.text||old.revision!==next.revision)kind='MODIFIED';return {stableCode,kind,...(old?{before:old.text}:{}),...(next?{after:next.text}:{}),affectedCaseIds:kind==='UNCHANGED'?[]:(links.get(old?.id||next?.id||'')||[])};});
}
export async function recordSnapshotImpact(tx:Prisma.TransactionClient,projectId:string,snapshotId:string,userId:string){
 const current=await tx.requirementSnapshot.findUniqueOrThrow({where:{id:snapshotId}}),previous=await tx.requirementSnapshot.findFirst({where:{projectId,id:{not:snapshotId}},orderBy:{createdAt:'desc'}});
 const after=current.items as unknown as SnapshotItem[],before=(previous?.items||[]) as unknown as SnapshotItem[];
 const ids=before.map(item=>item.id);const linked=ids.length?await tx.requirementCaseLink.findMany({where:{requirementId:{in:ids}}}):[];const links=new Map<string,string[]>();for(const link of linked)links.set(link.requirementId,[...(links.get(link.requirementId)||[]),link.testCaseId]);
 const changes=diffSnapshots(before,after,links),affected=[...new Set(changes.flatMap(change=>change.affectedCaseIds))];
 if(affected.length)await tx.testCase.updateMany({where:{id:{in:affected}},data:{stale:true,status:'draft',updatedBy:userId,version:{increment:1}}});
 const summary={added:changes.filter(v=>v.kind==='ADDED').length,modified:changes.filter(v=>v.kind==='MODIFIED').length,deleted:changes.filter(v=>v.kind==='DELETED').length,unchanged:changes.filter(v=>v.kind==='UNCHANGED').length,affectedCases:affected.length};
 await tx.requirementChangeSet.upsert({where:{projectId_toSnapshot:{projectId,toSnapshot:current.hash}},create:{projectId,fromSnapshot:previous?.hash,toSnapshot:current.hash,summary,changes:changes as unknown as Prisma.InputJsonValue,createdBy:userId},update:{fromSnapshot:previous?.hash,summary,changes:changes as unknown as Prisma.InputJsonValue}});
 return summary;
}

const safe=(value:string)=>value.replace(/[^a-z0-9]+/gi,' ').trim();
export function generatePlaywrightArtifact(testCase:{stableCode:string;title:string;preconditions:string;steps:{action:string;expectedResult:string}[]}){
 const title=JSON.stringify(`${testCase.stableCode} ${testCase.title}`),selectors=testCase.steps.map((step,index)=>({step:index+1,label:safe(step.action).slice(0,80),candidates:[{kind:'testId',value:`step-${index+1}`},{kind:'role',value:'button',name:safe(step.action).slice(0,80)},{kind:'text',value:safe(step.action).slice(0,80)}]}));
 const source=`import { test, expect, type Locator, type Page } from '@playwright/test';\n\nconst candidates = ${JSON.stringify(selectors,null,2)} as const;\n\nasync function healingLocator(page: Page, index: number): Promise<Locator> {\n  const entry = candidates[index];\n  for (const candidate of entry.candidates) {\n    const locator = candidate.kind === 'testId' ? page.getByTestId(candidate.value) : candidate.kind === 'role' ? page.getByRole(candidate.value as 'button', { name: candidate.name }) : page.getByText(candidate.value, { exact: false });\n    if (await locator.first().isVisible().catch(() => false)) {\n      if (candidate !== entry.candidates[0]) console.info('TESTPILOT_SELECTOR_FALLBACK', { step: entry.step, candidate });\n      return locator.first();\n    }\n  }\n  throw new Error('No selector candidate resolved for step ' + entry.step);\n}\n\ntest(${title}, async ({ page }) => {\n${testCase.steps.map((step,index)=>`  // ${safe(step.expectedResult)}\n  await (await healingLocator(page, ${index})).click();`).join('\n')}\n  await expect(page).toHaveURL(/.+/);\n});\n`;
 return {filename:`${testCase.stableCode.toLowerCase()}-${safe(testCase.title).toLowerCase().replaceAll(' ','-').slice(0,50)}.spec.ts`,source,selectors};
}

export async function intelligenceApi(req:Request,path:string[],userId:string):Promise<Response|undefined>{
 if(path[0]!=='projects'||!path[1])return;const projectId=path[1];
 if(!['intelligence','feedback','automation'].includes(path[2]||''))return;await membership(projectId,userId);
 if(path[2]==='intelligence'&&req.method==='GET'){
  const [changeSets,feedback,artifacts,runs]=await Promise.all([db.requirementChangeSet.findMany({where:{projectId},orderBy:{createdAt:'desc'},take:20}),db.feedbackEvent.groupBy({by:['category','disposition'],where:{projectId},_count:true,orderBy:{_count:{category:'desc'}}}),db.automationArtifact.findMany({where:{projectId},orderBy:{updatedAt:'desc'},include:{testCase:{select:{stableCode:true,title:true,status:true,stale:true}},repairs:{where:{status:'pending'},orderBy:{createdAt:'desc'}}}}),db.generationRun.findMany({where:{projectId},orderBy:{createdAt:'desc'},take:20})]);
  return Response.json({changeSets,feedback:feedback.map(v=>({category:v.category,disposition:v.disposition,count:v._count})),artifacts,runs});
 }
 if(path[2]==='feedback'&&req.method==='POST'){
  const body=z.object({testCaseId:z.uuid().optional(),category:z.enum(['missing_coverage','incorrect_step','ambiguous_wording','wrong_priority','wrong_type','other']),disposition:z.enum(['edited','rejected','accepted_with_note']),note:z.string().trim().max(2000).default(''),original:z.unknown().optional(),corrected:z.unknown().optional()}).strict().parse(await req.json());
  if(body.testCaseId&&await db.testCase.count({where:{id:body.testCaseId,projectId}})!==1)throw new ApiError(422,'VALIDATION_ERROR','The test case does not belong to this project.');
  const event=await db.$transaction(async tx=>{const saved=await tx.feedbackEvent.create({data:{...body,original:body.original as Prisma.InputJsonValue,corrected:body.corrected as Prisma.InputJsonValue,projectId,createdBy:userId}});await audit(tx,projectId,userId,'ai_feedback_recorded','FeedbackEvent',saved.id,undefined,{category:body.category,disposition:body.disposition});return saved;});return Response.json(event,{status:201});
 }
 if(path[2]==='automation'&&path[3]==='generate'&&req.method==='POST'){
  const body=z.object({testCaseIds:z.array(z.uuid()).min(1).max(100)}).strict().parse(await req.json());const cases=await db.testCase.findMany({where:{id:{in:[...new Set(body.testCaseIds)]},projectId,status:'approved',stale:false,deletedAt:null},include:{steps:{orderBy:{position:'asc'}}}});if(cases.length!==new Set(body.testCaseIds).size)throw new ApiError(422,'VALIDATION_ERROR','Only approved, current test cases can generate automation.');
  const saved=await db.$transaction(async tx=>{const results=[];for(const testCase of cases){const artifact=generatePlaywrightArtifact(testCase),hash=createHash('sha256').update(artifact.source).digest('hex');const row=await tx.automationArtifact.upsert({where:{testCaseId_framework:{testCaseId:testCase.id,framework:'playwright'}},create:{projectId,testCaseId:testCase.id,framework:'playwright',...artifact,status:'review',createdBy:userId,updatedBy:userId},update:{...artifact,status:'review',version:{increment:1},updatedBy:userId}});await audit(tx,projectId,userId,'automation_generated','AutomationArtifact',row.id,undefined,{testCaseId:testCase.id,hash,version:row.version});results.push(row);}return results;});return Response.json({artifacts:saved},{status:201});
 }
 if(path[2]==='automation'&&path[3]&&path[4]==='download'&&req.method==='GET'){
  const artifact=await db.automationArtifact.findFirst({where:{id:path[3],projectId}});if(!artifact)throw new ApiError(404,'NOT_FOUND','Automation artifact not found.');return new Response(artifact.source,{headers:{'Content-Type':'text/typescript; charset=utf-8','Content-Disposition':`attachment; filename*=UTF-8''${encodeURIComponent(artifact.filename)}`,'Cache-Control':'private, no-store'}});
 }
 if(path[2]==='automation'&&path[3]&&path[4]==='fallback'&&req.method==='POST'){
  const selector=z.object({kind:z.enum(['testId','role','text']),value:z.string().trim().min(1).max(500),name:z.string().trim().max(500).optional()}).strict(),body=z.object({step:z.number().int().positive(),failedSelector:selector,workingSelector:selector}).strict().parse(await req.json()),artifact=await db.automationArtifact.findFirst({where:{id:path[3],projectId}});if(!artifact)throw new ApiError(404,'NOT_FOUND','Automation artifact not found.');const entries=z.array(z.object({step:z.number().int().positive(),label:z.string(),candidates:z.array(selector)})).parse(artifact.selectors),entry=entries.find(item=>item.step===body.step);if(!entry)throw new ApiError(422,'VALIDATION_ERROR','The reported step is not part of this artifact.');const key=(item:z.infer<typeof selector>)=>JSON.stringify(item),working=key(body.workingSelector);if(!entry.candidates.some(item=>key(item)===working))throw new ApiError(422,'VALIDATION_ERROR','The working selector must be one of the governed fallback candidates.');entry.candidates=[body.workingSelector,...entry.candidates.filter(item=>key(item)!==working)];const start=artifact.source.indexOf('const candidates = '),end=artifact.source.indexOf(' as const;',start);if(start<0||end<0)throw new ApiError(409,'ARTIFACT_FORMAT_UNSUPPORTED','This artifact cannot be repaired automatically.');const proposedSource=`${artifact.source.slice(0,start)}const candidates = ${JSON.stringify(entries,null,2)}${artifact.source.slice(end)}`;const suggestion=await db.$transaction(async tx=>{const saved=await tx.automationRepairSuggestion.create({data:{artifactId:artifact.id,failedSelector:body.failedSelector,workingSelector:body.workingSelector,proposedSource,createdBy:userId}});await audit(tx,projectId,userId,'automation_repair_suggested','AutomationArtifact',artifact.id,undefined,{suggestionId:saved.id,step:body.step});return saved;});return Response.json(suggestion,{status:201});
 }
 if(path[2]==='automation'&&path[3]&&path[4]==='repairs'&&path[5]&&req.method==='POST'){
  const body=z.object({action:z.enum(['approve','reject'])}).strict().parse(await req.json()),artifact=await db.automationArtifact.findFirst({where:{id:path[3],projectId}});if(!artifact)throw new ApiError(404,'NOT_FOUND','Automation artifact not found.');const result=await db.$transaction(async tx=>{const suggestion=await tx.automationRepairSuggestion.findFirst({where:{id:path[5],artifactId:artifact.id,status:'pending'}});if(!suggestion)throw new ApiError(409,'REPAIR_NOT_PENDING','This repair suggestion was already reviewed.');if(body.action==='approve')await tx.automationArtifact.update({where:{id:artifact.id},data:{source:suggestion.proposedSource,version:{increment:1},status:'review',updatedBy:userId}});const saved=await tx.automationRepairSuggestion.update({where:{id:suggestion.id},data:{status:body.action==='approve'?'approved':'rejected',reviewedBy:userId,reviewedAt:new Date()}});await audit(tx,projectId,userId,`automation_repair_${saved.status}`,'AutomationArtifact',artifact.id,undefined,{suggestionId:saved.id});return saved;});return Response.json(result);
 }
}
