'use client';
import {useEffect,useState} from 'react';
import {api,locator} from './project-nav';
import type {CaseRecord} from './workbench';
type Req={id:string;stableCode:string;text:string};
type Editable={title:string;type:string;priority:string;preconditions:string;testData:string;postconditions:string;rationale:string;reviewerNotes:string;steps:{action:string;expectedResult:string}[]};
const blank:Editable={title:'',type:'other',priority:'medium',preconditions:'',testData:'',postconditions:'',rationale:'',reviewerNotes:'',steps:[{action:'',expectedResult:''}]};
const editable=(record:CaseRecord):Editable=>({title:record.title,type:record.type,priority:record.priority,preconditions:record.preconditions,testData:record.testData,postconditions:record.postconditions,rationale:record.rationale,reviewerNotes:record.reviewerNotes,steps:record.steps.map(s=>({action:s.action,expectedResult:s.expectedResult}))});
export function CaseEditor({projectId,record,onSaved,onClose,onRegenerate}:{projectId:string;record:CaseRecord|null;onSaved:()=>Promise<void>;onClose:()=>void;onRegenerate:(jobId:string)=>void}){
 const [form,setForm]=useState<Editable>(record?editable(record):blank),[current,setCurrent]=useState(record),[requirements,setRequirements]=useState<Req[]>([]),[links,setLinks]=useState(record?.links.map(l=>l.requirement.id)||[]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[history,setHistory]=useState<{version:number;data:Record<string,unknown>;reason:string;createdAt:string}[]>([]),[showHistory,setShowHistory]=useState(false),[note,setNote]=useState('');
 useEffect(()=>{api(`projects/${projectId}/requirements`).then(async d=>{let rows=d.requirements,cursor=d.next_cursor;while(cursor){const n=await api(`projects/${projectId}/requirements?cursor=${encodeURIComponent(cursor)}`);rows=rows.concat(n.requirements);cursor=n.next_cursor;}setRequirements(rows);}).catch(e=>setError(e.message));},[projectId]);
 async function refresh(){const d=await api(`projects/${projectId}/test-cases`);let rows:CaseRecord[]=d.cases,cursor=d.next_cursor;while(cursor){const n=await api(`projects/${projectId}/test-cases?cursor=${encodeURIComponent(cursor)}`);rows=rows.concat(n.cases);cursor=n.next_cursor;}const updated=rows.find(c=>c.id===current?.id);if(updated){setCurrent(updated);setForm(editable(updated));setLinks(updated.links.map(l=>l.requirement.id));}await onSaved();}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{if(current){await api(`test-cases/${current.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,version:current.version})});await refresh();}else{await api(`projects/${projectId}/test-cases`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,requirementIds:links})});await onSaved();onClose();}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function action(kind:'approve'|'reject'|'retain'|'regenerate'|'links'){if(!current)return;if(JSON.stringify(form)!==JSON.stringify(editable(current))){setError('Save your case changes before updating links, making a review decision, or regenerating.');return;}if(kind==='regenerate'&&!window.confirm('Regenerate this case from its source requirements? Your current case is retained in version history. The new version returns to draft for review.'))return;setError('');setBusy(true);try{if(kind==='regenerate'){const response=await api(`test-cases/${current.id}/regenerate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:current.version})});onRegenerate(response.job_id);onClose();}else if(kind==='links')await api(`test-cases/${current.id}/links`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requirementIds:links,version:current.version})});else await api(`test-cases/${current.id}/review`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:kind,note,version:current.version})});await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function loadHistory(){if(!current)return;try{const d=await api(`test-cases/${current.id}/history`);setHistory(d.versions);setShowHistory(!showHistory);}catch(e){setError((e as Error).message);}}
 const update=(key:keyof Editable,value:string)=>setForm({...form,[key]:value});
 return <><div className="modal-heading"><div><div className="eyebrow">{current?`${current.stableCode} · VERSION ${current.version}`:'ADD TO YOUR TEST SUITE'}</div><h2 id="case-editor-title">{current?'Review test case':'New manual test case'}</h2></div><button className="icon-button" aria-label="Close test case" onClick={onClose}>×</button></div>{error&&<div className="error-box" role="alert"><span>{error}</span>{current&&<button className="button secondary" onClick={()=>void refresh().then(()=>setError(''))}>Reload latest</button>}</div>}{current&&<div className="detail-badges"><span className={`badge status-${current.status}`}>{current.status}</span>{current.stale&&<span className="badge badge-amber">Stale · requirement revised</span>}<button className="text-button" onClick={()=>void loadHistory()}>Version history</button></div>}{showHistory&&<div className="version-history">{history.length?history.map(v=><details key={v.version}><summary>Version {v.version} · {v.reason} · {new Date(v.createdAt).toLocaleDateString()}</summary><div className="history-content"><h3>{String(v.data.title||'Test case')}</h3><p><strong>Status:</strong> {String(v.data.status||'draft')} · <strong>Type:</strong> {String(v.data.type||'other')}</p>{Boolean(v.data.preconditions)&&<p><strong>Preconditions:</strong> {String(v.data.preconditions)}</p>}{Array.isArray(v.data.steps)&&<ol>{v.data.steps.map((s:Record<string,unknown>,i:number)=><li key={i}><strong>{String(s.action||'No action recorded')}</strong><p>Expected: {String(s.expectedResult||s.expected_result||'Not recorded')}</p></li>)}</ol>}{Boolean(v.data.reviewerNotes)&&<p><strong>Reviewer notes:</strong> {String(v.data.reviewerNotes)}</p>}</div></details>):<p>No prior versions yet.</p>}</div>}
 <form className="case-edit-form" onSubmit={save}><label>Case title<input className="form-control" required maxLength={300} value={form.title} onChange={e=>update('title',e.target.value)}/></label><div className="form-columns"><label>Type<select className="form-control" value={form.type} onChange={e=>update('type',e.target.value)}>{['positive','negative','boundary','permission','other'].map(t=><option key={t}>{t}</option>)}</select></label><label>Priority<select className="form-control" value={form.priority} onChange={e=>update('priority',e.target.value)}>{['high','medium','low'].map(t=><option key={t}>{t}</option>)}</select></label></div><label>Preconditions<textarea className="form-control" value={form.preconditions} onChange={e=>update('preconditions',e.target.value)} rows={2}/></label><div className="section-toolbar"><h3>Test steps</h3><button type="button" className="text-button" onClick={()=>setForm({...form,steps:[...form.steps,{action:'',expectedResult:''}]})}>+ Add step</button></div>{form.steps.map((s,i)=><div className="step-editor" key={i}><div className="step-editor-heading"><strong>Step {i+1}</strong><button type="button" className="text-button danger" aria-label={`Remove step ${i+1}`} onClick={()=>setForm({...form,steps:form.steps.filter((_,n)=>n!==i)})}>Remove</button></div><label>Action<textarea className="form-control" rows={2} value={s.action} onChange={e=>setForm({...form,steps:form.steps.map((step,n)=>n===i?{...step,action:e.target.value}:step)})}/></label><label>Expected result<textarea className="form-control" rows={2} value={s.expectedResult} onChange={e=>setForm({...form,steps:form.steps.map((step,n)=>n===i?{...step,expectedResult:e.target.value}:step)})}/></label></div>)}{(['testData','postconditions','rationale','reviewerNotes'] as const).map(key=><label key={key}>{{testData:'Test data',postconditions:'Postconditions',rationale:'Rationale',reviewerNotes:'Reviewer notes'}[key]}<textarea className="form-control" rows={2} value={form[key]} onChange={e=>update(key,e.target.value)}/></label>)}<fieldset className="requirement-picker"><legend>Linked requirements</legend>{requirements.map(r=><label key={r.id}><input type="checkbox" checked={links.includes(r.id)} onChange={e=>setLinks(e.target.checked?[...links,r.id]:links.filter(v=>v!==r.id))}/><span><strong>{r.stableCode}</strong> {r.text}</span></label>)}{!requirements.length&&<p>No requirements yet. The case will appear in the unlinked queue.</p>}</fieldset><div className="modal-actions">{current&&<button type="button" className="button secondary" disabled={busy} onClick={()=>void action('links')}>Save requirement links</button>}<button className="button primary" disabled={busy}>{busy?'Saving…':current?'Save case changes':'Create manual case'}</button></div></form>
 {current&&<><section className="case-review-actions"><h3>Review decision</h3><p>Save your edits before approving. Approval requires complete steps and expected results.</p><label className="field-label">Decision note<textarea className="form-control" value={note} onChange={e=>setNote(e.target.value)} rows={2}/></label><div className="inline-actions"><button className="button primary" disabled={busy} onClick={()=>void action('approve')}>Approve case</button><button className="button secondary" disabled={busy} onClick={()=>void action('reject')}>Reject case</button>{current.stale&&<button className="button secondary" disabled={busy} onClick={()=>void action('retain')}>Retain after review</button>}</div><button className="text-button" disabled={busy} onClick={()=>void action('regenerate')}>Regenerate this case</button></section><h3>Source citations</h3>{current.citations?.length?current.citations.map(c=><div className="citation-card" key={c.id}><span className={`badge ${c.inferred?'badge-amber':''}`}>{c.inferred?'Inferred · reviewer verification required':locator(c.locator)}</span><blockquote>{c.quote||'No direct source quotation is available. Verify against the linked requirement.'}</blockquote>{c.sourceId&&<a className="text-link" href={`/api/v1/sources/${c.sourceId}/download`}>Original source ↗</a>}</div>):<p className="muted">Manual case: review the linked requirements for source context.</p>}</>}
 </>;
}





