'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useEffect, useRef, useState } from 'react';
import { Icon } from './shell';

type Project = { id: string; name: string; description: string | null; domain: string | null; _count: { sources: number; requirements: number; testCases: number }; approvedCount: number; draftCount: number; updatedAt: string };
export function Dashboard() {
  const [projects, setProjects] = useState<Project[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState(''), [search, setSearch] = useState(''), [saving, setSaving] = useState(false), [formError, setFormError] = useState('');
  const dialog = useRef<HTMLDialogElement>(null), createButton = useRef<HTMLButtonElement>(null), router = useRouter();
  const load = async () => { setLoading(true); setError(''); try { const r = await fetch('/api/v1/projects'); const data = await r.json(); if (!r.ok) throw new Error(data.error?.message || 'Projects could not be loaded.'); setProjects(data.projects); } catch (e) { setError(e instanceof Error ? e.message : 'Projects could not be loaded.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const open = () => { setFormError(''); dialog.current?.showModal(); };
  const close = () => { dialog.current?.close(); createButton.current?.focus(); };
  const create = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); setSaving(true); setFormError(''); try { const r = await fetch('/api/v1/projects', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: form.get('name'), description: form.get('description'), domain: form.get('domain') }) }); const data = await r.json(); if (!r.ok) throw new Error(data.error?.message || data.message || 'Unable to create project. Check the name and try again.'); router.push(`/projects/${data.project?.id || data.id}`); } catch (e) { setFormError(e instanceof Error ? e.message : 'Unable to create project.'); } finally { setSaving(false); } };
  const total = (field: keyof Project['_count']) => projects.reduce((n, p) => n + (p._count?.[field] || 0), 0);
  const approved = projects.reduce((n, p) => n + (p.approvedCount || 0), 0), visible = projects.filter(p => `${p.name} ${p.description || ''} ${p.domain || ''}`.toLowerCase().includes(search.toLowerCase()));
  return <><div className="eyebrow">YOUR TEST DESIGN WORKSPACE</div><div className="page-heading"><div><h1>Projects</h1><p>Turn requirements into tests you can trust and trace.</p></div><button className="button primary" ref={createButton} onClick={open}><Icon name="plus" size={18}/>Create project</button></div>
    <section className="intro-banner"><div className="intro-copy"><span className="badge badge-blue">FROM REQUIREMENTS TO REVIEW</span><h2>Better tests begin with clear requirements.</h2><p>Bring your sources, review the details, and build a traceable test suite.</p></div><ol className="journey"><li><span>01</span><strong>Import</strong><small>Ground in your sources</small></li><li><span>02</span><strong>Review</strong><small>Make every case count</small></li><li><span>03</span><strong>Export</strong><small>Share with confidence</small></li></ol></section>
    <section className="stats-grid" aria-label="Workspace totals">{[{label:'Total projects',value:projects.length,icon:'grid'},{label:'Source documents',value:total('sources'),icon:'document'},{label:'Requirements',value:total('requirements'),icon:'layers'},{label:'Approved cases',value:approved,icon:'check'}].map(s=><div className="stat-card" key={s.label}><div><span>{s.label}</span><strong>{loading?'—':s.value}</strong></div><span className={`stat-icon ${s.icon==='check'?'green':''}`}><Icon name={s.icon}/></span></div>)}</section>
    <div className="section-toolbar"><div className="section-title"><h2>All projects</h2><span className="count-pill">{projects.length}</span></div><div className="search-input"><Icon name="search" size={18}/><input aria-label="Search projects" placeholder="Search projects…" value={search} onChange={e=>setSearch(e.target.value)}/></div></div>
    {error ? <div className="error-box" role="alert">{error}<button className="button secondary" onClick={()=>void load()}>Try again</button></div> : loading ? <div className="project-grid" aria-label="Loading projects">{[1,2,3].map(i=><div key={i} className="project-card skeleton">Loading project…</div>)}</div> : visible.length ? <div className="project-grid">{visible.map(p=><Link key={p.id} className="project-card" href={`/projects/${p.id}`}><div className="project-card-top"><span className="project-symbol"><Icon name="layers" size={23}/></span><span className="badge">{p.domain || 'General'}</span></div><h3>{p.name}</h3><p className="project-description">{p.description || 'A workspace for source-grounded requirements and reviewable test cases.'}</p><div className="project-metrics"><div><strong>{p._count?.sources || 0}</strong><span>Sources</span></div><div><strong>{p._count?.requirements || 0}</strong><span>Requirements</span></div><div><strong>{p._count?.testCases || 0}</strong><span>Test cases</span></div></div><div className="project-review"><span><i className="status-dot amber"/>{p.draftCount || 0} draft</span><span><i className="status-dot"/>{p.approvedCount || 0} approved</span></div><div className="project-card-footer"><span>Updated {new Date(p.updatedAt).toLocaleDateString('en', {month:'short',day:'numeric'})}</span><span className="open-project">Open project <Icon name="arrow" size={16}/></span></div></Link>)}</div> : <div className="empty-state"><span className="project-symbol"><Icon name="grid" size={26}/></span><h2>{search?'No matching projects':'Your first test suite starts here'}</h2><p>{search?'Try another project name or domain.':'Create a project, import your requirements, then review and export your test cases.'}</p>{!search&&<button className="button primary" onClick={open}><Icon name="plus" size={18}/>Create your first project</button>}</div>}
    <dialog aria-labelledby="create-project-title" ref={dialog} className="modal" onClose={()=>createButton.current?.focus()}><form onSubmit={create}><div className="modal-heading"><div><div className="eyebrow">NEW WORKSPACE PROJECT</div><h2 id="create-project-title">Create project</h2></div><button type="button" className="icon-button" aria-label="Close create project" onClick={close}>×</button></div><p>Keep your requirements, test cases, and review history together.</p><label>Project name <span className="required">*</span><input name="name" required maxLength={120} placeholder="e.g. Customer portal" autoFocus/></label><label>Description<textarea name="description" rows={3} maxLength={2000} placeholder="What will you be testing?"/></label><label>Domain<input name="domain" maxLength={100} placeholder="e.g. Banking, E-commerce, SaaS"/></label>{formError&&<div className="error-box" role="alert">{formError}</div>}<div className="modal-actions"><button type="button" className="button secondary" onClick={close}>Cancel</button><button className="button primary" disabled={saving}>{saving?'Creating…':'Create project'}<Icon name="arrow" size={18}/></button></div></form></dialog>
  </>;
}

