'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {api,ProjectNav} from './project-nav';
import {Icon} from './shell';
type Change={stableCode:string;kind:string;before?:string;after?:string;affectedCaseIds:string[]};
type ChangeSet={id:string;toSnapshot:string;summary:{added:number;modified:number;deleted:number;unchanged:number;affectedCases:number};changes:Change[];createdAt:string};
type Artifact={id:string;filename:string;version:number;status:string;updatedAt:string;testCase:{stableCode:string;title:string;status:string;stale:boolean};repairs:{id:string;workingSelector:Record<string,string>;createdAt:string}[]};
type AdvisoryRun={id:string;agentKey:string;status:string;startedAt:string;outputRef:Record<string,unknown>;findings:Array<{id:string;severity:string;message:string}>};type Data={changeSets:ChangeSet[];feedback:{category:string;disposition:string;count:number}[];artifacts:Artifact[];advisoryRuns:AdvisoryRun[]};
export function IntelligenceCenter({id}:{id:string}){
 const [data,setData]=useState<Data|null>(null),[project,setProject]=useState('Project'),[cases,setCases]=useState<{id:string;stableCode:string;title:string;status:string;stale:boolean}[]>([]),[selected,setSelected]=useState<string[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{const [result,p,c]=await Promise.all([api(`projects/${id}/intelligence`),api(`projects/${id}`),api(`projects/${id}/test-cases`)]);setData(result);setProject((p.project||p).name);setCases(c.cases);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void load();},[id]);
 async function generate(){setBusy(true);setError('');try{await api(`projects/${id}/automation/generate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({testCaseIds:selected})});setSelected([]);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function analyze(){setBusy(true);setError('');try{await api(`projects/${id}/intelligence/analyze`,{method:'POST'});await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function reviewRepair(artifactId:string,repairId:string,action:'approve'|'reject'){setBusy(true);setError('');try{await api(`projects/${id}/automation/${artifactId}/repairs/${repairId}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const eligible=cases.filter(item=>item.status==='approved'&&!item.stale),latest=data?.changeSets[0];
 return <><Link href={`/projects/${id}`} className="back-link">← {project}</Link><div className="page-heading"><div><div className="eyebrow">QUALITY INTELLIGENCE</div><h1>Reliability & change impact</h1><p>See requirement drift, human correction signals, and governed automation assets.</p></div><div className="heading-actions"><span className="badge badge-blue">Human approval enforced</span><button className="button primary" disabled={busy} onClick={()=>void analyze()}>{busy?'Analyzing…':'Run advisory analysis'}</button></div></div><ProjectNav id={id} active="intelligence"/>{error&&<div className="error-box" role="alert">{error}</div>}
 <section className="metric-grid intelligence-metrics"><div className="metric-card"><span>Requirement changes</span><strong>{latest?latest.summary.added+latest.summary.modified+latest.summary.deleted:0}</strong><small>Latest confirmed revision</small></div><div className="metric-card"><span>Cases needing revision</span><strong>{latest?.summary.affectedCases||0}</strong><small>Automatically flagged</small></div><div className="metric-card"><span>Human feedback</span><strong>{data?.feedback.reduce((sum,row)=>sum+row.count,0)||0}</strong><small>Correction signals retained</small></div><div className="metric-card"><span>Automation assets</span><strong>{data?.artifacts.length||0}</strong><small>Versioned Playwright drafts</small></div></section>
 <section className="panel"><div className="section-toolbar"><div><h2>Advisory agent review</h2><p className="muted">Recommendations are evidence for a reviewer. They never approve or modify artifacts automatically.</p></div><Link className="text-link" href="/findings">Open Findings Inbox</Link></div><div className="advisory-grid">{['requirement-quality','review-assistant','coverage-gap','change-impact'].map(key=>{const run=data?.advisoryRuns.find(item=>item.agentKey===key);return <article className="advisory-card" key={key}><div><span className={`status-dot ${run?.status==='SUCCEEDED'?'green':'amber'}`}/><strong>{key.replaceAll('-',' ')}</strong></div><span className={`badge status-${run?.status?.toLowerCase()||'draft'}`}>{run?.status?.replaceAll('_',' ')||'Not run'}</span><b>{run?.findings.length||0}</b><small>open recommendation{run?.findings.length===1?'':'s'}</small>{run&&<time>{new Date(run.startedAt).toLocaleString()}</time>}</article>})}</div></section>
 <div className="intelligence-grid"><section className="panel"><div className="section-toolbar"><div><h2>Semantic change impact</h2><p className="muted">Stable requirement IDs are compared across immutable snapshots.</p></div>{latest&&<span className="badge">{new Date(latest.createdAt).toLocaleString()}</span>}</div>{latest?<><div className="change-summary"><span className="badge status-approved">+ {latest.summary.added} added</span><span className="badge badge-amber">~ {latest.summary.modified} modified</span><span className="badge status-rejected">− {latest.summary.deleted} deleted</span><span className="badge">= {latest.summary.unchanged} unchanged</span></div><div className="impact-list">{latest.changes.filter(change=>change.kind!=='UNCHANGED').map(change=><article key={change.stableCode}><div><strong>{change.stableCode}</strong><span className="badge">{change.kind}</span></div>{change.before&&<p><small>Before</small>{change.before}</p>}{change.after&&<p><small>After</small>{change.after}</p>}<footer>{change.affectedCaseIds.length} linked case{change.affectedCaseIds.length===1?'':'s'} flagged for revision</footer></article>)}</div></>:<div className="empty-state compact"><Icon name="activity" size={30}/><h3>No revision comparison yet</h3><p>Confirm requirements, then confirm a changed revision to produce impact analysis.</p></div>}</section>
 <section className="panel"><h2>Human correction signals</h2><p className="muted">Edits and rejections are classified so recurring AI weaknesses can become prompt rules and regression examples.</p>{data?.feedback.length?<div className="feedback-list">{data.feedback.map(row=><div key={`${row.category}-${row.disposition}`}><strong>{row.category.replaceAll('_',' ')}</strong><span>{row.disposition.replaceAll('_',' ')}</span><b>{row.count}</b></div>)}</div>:<div className="empty-state compact"><h3>No correction patterns yet</h3><p>Feedback captured during case review will be summarized here.</p></div>}</section></div>
 <section className="panel automation-panel"><div className="section-toolbar"><div><h2>Playwright automation drafts</h2><p className="muted">Generate code from approved, current cases with ranked locator candidates and fallback logging.</p></div><button className="button primary" disabled={busy||!selected.length} onClick={()=>void generate()}>{busy?'Working…':`Generate ${selected.length||''} selected`}</button></div><div className="automation-layout"><div><h3>Eligible approved cases</h3>{eligible.map(item=><label className="check-row" key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={e=>setSelected(e.target.checked?[...selected,item.id]:selected.filter(value=>value!==item.id))}/><span><strong>{item.stableCode}</strong>{item.title}</span></label>)}{!eligible.length&&<p className="muted">Approve a current test case to enable automation generation.</p>}</div><div><h3>Generated artifacts</h3>{data?.artifacts.map(item=><div className="artifact-row" key={item.id}><div><strong>{item.filename}</strong><small>{item.testCase.stableCode} · Version {item.version} · {item.status}</small>{item.repairs.map(repair=><span className="repair-review" key={repair.id}><small>Fallback found: {repair.workingSelector.kind} {repair.workingSelector.value}</small><button className="text-button" disabled={busy} onClick={()=>void reviewRepair(item.id,repair.id,'approve')}>Approve repair</button><button className="text-button" disabled={busy} onClick={()=>void reviewRepair(item.id,repair.id,'reject')}>Reject</button></span>)}</div><a className="button secondary" href={`/api/v1/projects/${id}/automation/${item.id}/download`}>Download</a></div>)}{!data?.artifacts.length&&<p className="muted">No automation drafts have been generated.</p>}</div></div></section></>;
}
