'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {Icon} from './shell';
import {api,ProjectNav} from './project-nav';
export type Source={id:string;filename:string;status:string;size:number;pageCount?:number;createdAt:string;warnings?:unknown[];error?:string};
type Project={id:string;name:string;description:string;domain:string;sources:Source[];_count?:Record<string,number>;counts?:Record<string,number>;auditEvents?:{id:string;action:string;createdAt:string}[];recentActivity?:{id:string;action:string;createdAt:string}[]};
export function ProjectWorkspace({id}:{id:string}){
 const [project,setProject]=useState<Project|null>(null),[error,setError]=useState('');
 async function load(){try{const d=await api(`projects/${id}`);setProject(d.project||d);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void load();},[id]);
 async function remove(s:Source){if(!window.confirm(`Delete ${s.filename}? Extracted requirements will be removed. Derived data must be regenerated. Sources cannot be deleted after generation.`))return;try{await api(`sources/${s.id}`,{method:'DELETE'});await load();}catch(e){setError((e as Error).message);}}
 if(!project)return <div className={error?'error-box':'panel'} role="status">{error||'Loading project workspace…'}</div>;
 const counts=project.counts||project._count||{}, sources=project.sources||[],activity=project.auditEvents||project.recentActivity||[];
 return <><Link className="back-link" href="/projects">← All projects</Link><div className="page-heading"><div><div className="eyebrow">PROJECT WORKSPACE · {project.domain||'GENERAL'}</div><h1>{project.name}</h1><p>{project.description||'Source-grounded requirements, reviewable test cases.'}</p></div><Link href={`/projects/${id}/requirements#import`} className="button primary"><Icon name="plus" size={18}/>Upload requirements</Link></div><ProjectNav id={id} active="overview"/>{error&&<div className="error-box" role="alert">{error}</div>}
 <section className="panel pipeline"><div className="section-title"><h2>Your test design journey</h2><span className="badge badge-blue">HUMAN REVIEW AT EVERY STEP</span></div><ol>{[{label:'Source uploaded',done:sources.some(s=>['succeeded','ready','extracted'].includes(s.status)),route:'requirements'},{label:'Requirements reviewed',done:(counts.confirmedRequirements||0)>0,route:'requirements'},{label:'Cases generated',done:(counts.testCases||0)>0,route:'test-cases'},{label:'Coverage reviewed',done:(counts.testCases||0)>0&&(counts.approvedCount||counts.approved||0)===(counts.testCases||0),route:'traceability'},{label:'Exported',done:(counts.exports||0)>0,route:'traceability'}].map((s,i)=><li key={s.label} className={s.done?'complete':''}><span>{s.done?'✓':i+1}</span><Link href={`/projects/${id}/${s.route}`}>{s.label}</Link></li>)}</ol></section>
 <div className="stats-grid">{[['Source documents',sources.length],['Requirements',counts.requirements||0],['Test cases',counts.testCases||0],['Approved cases',counts.approvedCount||counts.approved||0]].map(([label,value])=><div className="stat-card" key={label}><div><span>{label}</span><strong>{value}</strong></div></div>)}</div>
 <div className="workspace-columns"><section className="panel"><div className="section-toolbar"><h2>Source documents <span className="count-pill">{sources.length}</span></h2><Link className="text-link" href={`/projects/${id}/requirements#import`}>+ Add source</Link></div>{sources.length?<div className="source-list">{sources.map(s=><div className="source-row" key={s.id}><span className="project-symbol"><Icon name="document"/></span><div className="source-info"><a className="text-link" href={`/api/v1/sources/${s.id}/download`}>{s.filename}</a><small>{new Date(s.createdAt).toLocaleDateString()} · {Math.ceil(s.size/1024)} KB{s.pageCount?` · ${s.pageCount} pages`:''}</small>{s.error&&<p className="error-text">{s.error}</p>}{(s.warnings||[]).map((w,i)=><p className="warning-text" key={i}>{typeof w==='string'?w:JSON.stringify(w)}</p>)}</div><span className={`badge status-${s.status}`}>{s.status}</span><button className="text-button danger" onClick={()=>void remove(s)} aria-label={`Delete ${s.filename}`}>Delete</button></div>)}</div>:<div className="empty-state compact"><Icon name="document" size={32}/><h3>Start with your source of truth</h3><p>Upload a PDF, DOCX, or TXT file, or paste a user story.</p><Link className="button primary" href={`/projects/${id}/requirements#import`}>Import requirements</Link></div>}</section><section className="panel activity-panel"><h2>Recent activity</h2>{activity.length?activity.slice(0,8).map(a=><div className="activity-item" key={a.id}><span className="status-dot"/><div><strong>{a.action.replace(/_/g,' ')}</strong><small>{new Date(a.createdAt).toLocaleString()}</small></div></div>):<p className="muted">Project created. Import a source to begin your review history.</p>}<div className="review-note"><Icon name="check"/><p>Every extracted requirement keeps its source reference so you can review it in context.</p></div></section></div></>;
}

