'use client';
import Link from 'next/link';
import {useCallback,useEffect,useRef,useState} from 'react';
import {api,ProjectNav} from './project-nav';
import {Icon} from './shell';

type AuthoredDocument={id:string;projectId:string;title:string;templateType:string;content:string;status:string;version:number;updatedAt:string;revisions?:{id:string;version:number;title:string;createdAt:string}[]};
const templates=[['SIMPLE_PRD','Simple PRD','Purpose, users, requirements and acceptance criteria'],['BRD','Business requirements','Objectives, scope, stakeholders and business rules'],['SRS','Software specification','Functional, interface and quality requirements'],['AGILE_STORIES','Epic and user stories','Stories, acceptance criteria and dependencies'],['API_REQUIREMENTS','API requirements','Consumers, endpoints, validation and security'],['DATA_MIGRATION','Data migration','Mappings, reconciliation, cutover and rollback'],['BLANK','Blank document','A clean structured document']] as const;
export function RequirementAuthor({projectId}:{projectId:string}){
 const [projectName,setProjectName]=useState('Project'),[documents,setDocuments]=useState<AuthoredDocument[]>([]),[document,setDocument]=useState<AuthoredDocument|null>(null),[title,setTitle]=useState(''),[content,setContent]=useState(''),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[status,setStatus]=useState(''),[error,setError]=useState(''),[creating,setCreating]=useState(false),[aiBusy,setAiBusy]=useState(false),[uploadBusy,setUploadBusy]=useState(false),[aiDraft,setAiDraft]=useState<Record<string,string>>({projectType:'APPLICATION'}),[aiDraftStatus,setAiDraftStatus]=useState('');
 const aiDialog=useRef<HTMLDialogElement>(null),aiForm=useRef<HTMLFormElement>(null),fileRef=useRef<HTMLInputElement>(null),saveTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const select=(item:AuthoredDocument)=>{setDocument(item);setTitle(item.title);setContent(item.content);setDirty(false);setStatus(item.status==='SUBMITTED'?'Submitted for extraction':'All changes saved');};
 const load=useCallback(async()=>{try{const [project,result]=await Promise.all([api(`projects/${projectId}`),api(`projects/${projectId}/authoring-documents`)]);setProjectName(project.name);setDocuments(result.documents);if(result.documents.length&&!document)select(await api(`authoring-documents/${result.documents[0].id}`));}catch(e){setError((e as Error).message);}},[projectId,document]);
 useEffect(()=>{void load();const saved=localStorage.getItem(`testpilot-ai-brief-${projectId}`);if(saved){try{setAiDraft(JSON.parse(saved));setAiDraftStatus('Recovered saved draft');}catch{localStorage.removeItem(`testpilot-ai-brief-${projectId}`);}}},[load,projectId]);
 const save=useCallback(async()=>{if(!document||!dirty||saving)return;setSaving(true);setStatus('Saving…');try{const updated=await api(`authoring-documents/${document.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,content,version:document.version})});setDocument(updated);setDocuments(items=>items.map(item=>item.id===updated.id?updated:item));setDirty(false);setStatus(`Saved version ${updated.version}`);}catch(e){setError((e as Error).message);setStatus('Save failed');}finally{setSaving(false);}},[document,dirty,saving,title,content]);
 useEffect(()=>{if(!dirty)return;if(saveTimer.current)clearTimeout(saveTimer.current);saveTimer.current=setTimeout(()=>void save(),1200);return()=>{if(saveTimer.current)clearTimeout(saveTimer.current);};},[dirty,save]);
 async function createDocument(templateType:string){setCreating(true);setError('');try{const created=await api(`projects/${projectId}/authoring-documents`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:`${projectName} Requirements`,templateType})});setDocuments(items=>[created,...items]);select(created);}catch(e){setError((e as Error).message);}finally{setCreating(false);}}
 async function structure(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setAiBusy(true);setError('');const form=Object.fromEntries(new FormData(event.currentTarget).entries());try{const response=await fetch('/api/generate-prd',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,projectId})}),result=await response.json();if(!response.ok)throw new Error(result.message||'Requirement analysis failed.');setTitle(String(form.title));setContent(result.document);setDirty(true);setStatus(`${result.analysis.completenessScore}% complete · ${result.analysis.ambiguityFlags.length} ambiguity flags · validated in ${result.attempts} attempts`);aiDialog.current?.close();}catch(e){setError((e as Error).message);}finally{setAiBusy(false);}}
 function captureAiDraft(){if(!aiForm.current)return;const value=Object.fromEntries(new FormData(aiForm.current).entries()) as Record<string,string>;setAiDraft(value);localStorage.setItem(`testpilot-ai-brief-${projectId}`,JSON.stringify(value));setAiDraftStatus('Autosaved locally');}
 async function process(){if(!document)return;await save();setSaving(true);try{const result=await api(`authoring-documents/${document.id}/process`,{method:'POST'});setStatus(`Submitted for extraction · job ${String(result.job_id).slice(0,8)}`);window.location.href=`/projects/${projectId}/requirements`;}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
 async function uploadRevised(){const file=fileRef.current?.files?.[0];if(!file)return;if(file.size>10*1024*1024){setError('The revised document must be 10 MB or smaller.');return;}setUploadBusy(true);setError('');try{const body=new FormData();body.append('file',file);await api(`projects/${projectId}/sources`,{method:'POST',body});window.location.href=`/projects/${projectId}/requirements`;}catch(e){setError((e as Error).message);}finally{setUploadBusy(false);}}
 return <><Link className="back-link" href={`/projects/${projectId}`}>← {projectName}</Link><div className="page-heading"><div><div className="eyebrow">REQUIREMENT AUTHORING</div><h1>Requirements document</h1><p>Author, review and version your source before extracting testable requirements.</p></div><div className="page-actions"><button className="button secondary" onClick={()=>aiDialog.current?.showModal()} disabled={!document}>AI structure</button>{document&&<><a className="button secondary" href={`/api/v1/authoring-documents/${document.id}/download?format=docx`}>Download DOCX</a><button className="button primary" disabled={saving||dirty} onClick={()=>void process()}>Process for extraction</button></>}</div></div><ProjectNav id={projectId} active="author"/>{error&&<div className="error-box" role="alert">{error}<button className="button secondary" onClick={()=>setError('')}>Dismiss</button></div>}
 {!document?<section className="panel"><div className="section-title"><div><h2>Choose a starting template</h2><p className="muted">Every template remains editable and is saved to project history.</p></div></div><div className="template-grid">{templates.map(([value,name,description])=><button key={value} disabled={creating} onClick={()=>void createDocument(value)}><span className="project-symbol"><Icon name="document"/></span><strong>{name}</strong><small>{description}</small></button>)}</div></section>:<div className="authoring-layout"><aside className="panel document-sidebar"><div className="section-title"><h2>Documents</h2><button className="text-button" onClick={()=>setDocument(null)}>+ New</button></div>{documents.map(item=><button className={item.id===document.id?'selected':''} key={item.id} onClick={async()=>select(await api(`authoring-documents/${item.id}`))}><strong>{item.title}</strong><small>Version {item.version} · {item.status.toLowerCase()}</small></button>)}<hr/><label className="button secondary file-button">Upload revised Word file<input ref={fileRef} type="file" accept=".docx,.pdf,.txt" onChange={()=>void uploadRevised()}/></label>{uploadBusy&&<small>Uploading and validating…</small>}</aside><section className="panel editor-panel"><div className="editor-status"><span>{status}</span><span>Version {document.version}</span></div><label>Document title<input value={title} maxLength={120} onChange={e=>{setTitle(e.target.value);setDirty(true);setStatus('Unsaved changes');}}/></label><label>Structured document<textarea className="authoring-editor" aria-label="Requirements document content" value={content} maxLength={100000} onChange={e=>{setContent(e.target.value);setDirty(true);setStatus('Unsaved changes');}}/></label><div className="editor-footer"><span>{content.length.toLocaleString()} / 100,000 characters</span><div><a className="text-link" href={`/api/v1/authoring-documents/${document.id}/download?format=md`}>Download Markdown</a><button className="button secondary" disabled={!dirty||saving} onClick={()=>void save()}>{saving?'Saving…':'Save now'}</button></div></div>{document.revisions?.length?<details className="version-history"><summary>Version history ({document.revisions.length})</summary>{document.revisions.map(item=><p key={item.id}>Version {item.version} · {new Date(item.createdAt).toLocaleString()}</p>)}</details>:null}</section></div>}
 <dialog ref={aiDialog} className="modal document-builder" aria-labelledby="author-ai-title"><form ref={aiForm} onSubmit={structure} onInput={captureAiDraft}><div className="modal-heading"><div><div className="eyebrow">AI ASSISTED · HUMAN REVIEW REQUIRED</div><h2 id="author-ai-title">Structure this document</h2></div><button type="button" className="icon-button" onClick={()=>aiDialog.current?.close()}>×</button></div><p>Describe the product. The generated draft replaces the editor content only after you review and save it.</p><div className="form-grid"><label>Document title<input name="title" required minLength={3} maxLength={120} defaultValue={aiDraft.title||title}/></label><label>Project type<select name="projectType" defaultValue={aiDraft.projectType||'APPLICATION'}><option>APPLICATION</option><option>API</option><option>MOBILE</option><option>DATA</option><option>INTEGRATION</option><option>MIGRATION</option><option>OTHER</option></select></label></div><label>Product overview<textarea name="overview" required minLength={20} rows={3} defaultValue={aiDraft.overview}/></label><label>Primary users<textarea name="users" required minLength={3} rows={2} defaultValue={aiDraft.users}/></label><div className="form-grid"><label>In-scope items<textarea name="inScope" rows={3} defaultValue={aiDraft.inScope}/></label><label>Out-of-scope items<textarea name="outOfScope" rows={3} defaultValue={aiDraft.outOfScope}/></label></div><label>Capabilities<textarea name="capabilities" required minLength={10} rows={4} defaultValue={aiDraft.capabilities} placeholder="One capability per line"/></label><label>Business rules<textarea name="businessRules" rows={3} defaultValue={aiDraft.businessRules}/></label><label>Integrations and system dependencies<textarea name="integrations" rows={3} defaultValue={aiDraft.integrations}/></label><label>Assumptions and risks<textarea name="assumptionsRisks" rows={3} defaultValue={aiDraft.assumptionsRisks}/></label><label>Constraints and quality needs<textarea name="constraints" rows={3} defaultValue={aiDraft.constraints}/></label><label>Acceptance criteria<textarea name="acceptanceCriteria" rows={3} defaultValue={aiDraft.acceptanceCriteria}/></label><div className="builder-save-status" role="status">{aiDraftStatus}</div><div className="modal-actions"><button type="button" className="button secondary" onClick={()=>aiDialog.current?.close()}>Close</button><button type="button" className="button secondary" onClick={()=>{captureAiDraft();setAiDraftStatus(`Draft saved at ${new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`);}}>Save draft</button><button className="button primary" disabled={aiBusy}>{aiBusy?'Structuring…':'Create structured draft'}</button></div></form></dialog></>;
}
