'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {Icon} from './shell';
import {api,locator,ProjectNav} from './project-nav';
import type {Source} from './project-workspace';
type Requirement={id:string;stableCode:string;text:string;sourceLocator:Record<string,unknown>;excerpt:string;revision:number;version:number;included:boolean;confidence:string;category?:string;parentStory?:string;inferred:boolean;source?:Source;sourceId?:string};
type Job={id:string;status:string;progress:number;stage:string;error?:string};
export function Requirements({id}:{id:string}){
 const [name,setName]=useState('Project'),[requirements,setRequirements]=useState<Requirement[]>([]),[sources,setSources]=useState<Source[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[mode,setMode]=useState('file'),[text,setText]=useState(''),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[job,setJob]=useState<Job|null>(null),[selected,setSelected]=useState<string[]>([]),[editing,setEditing]=useState<string|null>(null),[editText,setEditText]=useState(''),[excerpt,setExcerpt]=useState<Requirement|null>(null),[sort,setSort]=useState('code'),[filter,setFilter]=useState('all'),[split,setSplit]=useState<Requirement|null>(null),[splitText,setSplitText]=useState(''),[snapshot,setSnapshot]=useState(''),[confirming,setConfirming]=useState(false);
 const drawer=useRef<HTMLDialogElement>(null),splitDialog=useRef<HTMLDialogElement>(null);
 async function load(){try{const [p,r]=await Promise.all([api(`projects/${id}`),api(`projects/${id}/requirements`)]);const project=p.project||p;setName(project.name);setSources(project.sources||[]);let rows:Requirement[]=r.requirements;let cursor=r.next_cursor;while(cursor){const next=await api(`projects/${id}/requirements?cursor=${encodeURIComponent(cursor)}`);rows=rows.concat(next.requirements);cursor=next.next_cursor;}setRequirements(rows);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[id]);
 useEffect(()=>{if(!job||['succeeded','failed'].includes(job.status))return;const interval=setInterval(async()=>{try{const d=await api(`jobs/${job.id}`);const j=d.job||d;setJob(j);if(j.status==='succeeded'||j.status==='failed'){setBusy(false);await load();if(j.error)setError(j.error);}}catch(e){setError((e as Error).message);setBusy(false);}},1200);return()=>clearInterval(interval);},[job?.id,job?.status]);
 async function upload(e:React.FormEvent){e.preventDefault();setError('');if(mode==='file'&&!file){setError('Choose a PDF, DOCX, or TXT file first.');return;}if(file&&mode==='file'&&file.size>10*1024*1024){setError('This file exceeds 10 MB. Choose a smaller document.');return;}setBusy(true);try{let init:RequestInit;if(mode==='file'){const body=new FormData();body.append('file',file!);init={method:'POST',body};}else init={method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,filename:'Pasted user story.txt'})};const d=await api(`projects/${id}/sources`,init);setJob({id:d.job_id||d.job?.id,status:'queued',progress:0,stage:'queued'});await load();}catch(e){setError((e as Error).message);setBusy(false);}}
 async function update(r:Requirement,changes:Record<string,unknown>){setError('');try{await api(`requirements/${r.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...changes,version:r.version})});setEditing(null);setSnapshot('');await load();}catch(e){setError((e as Error).message);}}
 async function merge(){setError('');try{await api(`projects/${id}/requirements/merge`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requirements:requirements.filter(r=>selected.includes(r.id)).map(r=>({id:r.id,version:r.version}))})});setSelected([]);setSnapshot('');await load();}catch(e){setError((e as Error).message);}}
 async function doSplit(e:React.FormEvent){e.preventDefault();if(!split)return;setError('');try{const texts=splitText.split(/\n\s*\n/).map(t=>t.trim()).filter(Boolean);if(texts.length<2)throw new Error('Enter at least two requirements separated by a blank line.');await api(`requirements/${split.id}/split`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({texts,version:split.version})});splitDialog.current?.close();setSnapshot('');await load();}catch(e){setError((e as Error).message);}}
 async function confirmRequirements(){setError('');setConfirming(true);try{const d=await api(`projects/${id}/requirements/confirm`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requirements:requirements.filter(r=>r.included).map(r=>({id:r.id,revision:r.revision}))})});setSnapshot(d.snapshot_hash);await load();}catch(e){setError((e as Error).message);}finally{setConfirming(false);}}
 const rows=requirements.filter(r=>filter==='all'||(filter==='included'?r.included:!r.included)).sort((a,b)=>sort==='source'?(a.source?.filename||'').localeCompare(b.source?.filename||''):a.stableCode.localeCompare(b.stableCode));
 return <><Link className="back-link" href={`/projects/${id}`}>← {name}</Link><div className="page-heading"><div><div className="eyebrow">SOURCE-GROUNDED TEST DESIGN</div><h1>Requirements</h1><p>Import your sources. Review what matters. Keep the context.</p></div><span className="badge badge-blue">{requirements.filter(r=>r.included).length} included for review</span></div><ProjectNav id={id} active="requirements"/>{error&&<div className="error-box" role="alert"><span>{error}</span><button className="button secondary" onClick={()=>{setError('');void load();}}>Reload latest</button></div>}
 <section className="panel import-panel" id="import"><div><div className="section-title"><h2>Import requirements</h2><span className="badge">PDF · DOCX · TXT</span></div><p className="muted">Your original source is retained, with references for every extracted item.</p></div><div className="segmented"><button type="button" className={mode==='file'?'selected':''} onClick={()=>setMode('file')}>Upload a file</button><button type="button" className={mode==='paste'?'selected':''} onClick={()=>setMode('paste')}>Paste a user story</button></div><form onSubmit={upload}>{mode==='file'?<label className="drop-zone"><span className="project-symbol"><Icon name="document" size={25}/></span><strong>{file?file.name:'Choose a requirements document'}</strong><span>{file?`${(file.size/1024).toFixed(1)} KB`:'Text-based PDF, DOCX, or UTF-8 TXT · Maximum 10 MB'}</span><input type="file" accept=".pdf,.docx,.txt" aria-label="Requirements document" onChange={e=>setFile(e.target.files?.[0]||null)}/></label>:<label className="field-label">User story and acceptance criteria<textarea className="form-control" rows={5} maxLength={50000} required value={text} onChange={e=>setText(e.target.value)} placeholder="As a user, I want to…\n1. The system shall…"/><span className="muted">{text.length.toLocaleString()} / 50,000 characters</span></label>}<div className="import-actions"><span className="muted">Documents are source data. Embedded instructions are ignored.</span><button className="button primary" disabled={busy}>{busy?'Processing…':'Extract requirements'}<Icon name="arrow" size={17}/></button></div></form>{job&&<div className={`job-progress status-${job.status}`} role="status"><strong>{job.status==='succeeded'?'Extraction complete':job.status==='failed'?'Extraction failed':`Extracting · ${job.stage}`}</strong><progress max={100} value={job.progress||0}/><span>{job.error||`${job.progress||0}% · ${job.status}`}</span></div>}</section>
 {sources.filter(s=>s.error||(s.warnings||[]).length).map(s=><div key={s.id} className="warning-box"><strong>{s.filename}</strong>{s.error&&<p>{s.error}</p>}{(s.warnings||[]).map((w,i)=><p key={i}>{typeof w==='string'?w:JSON.stringify(w)}</p>)}</div>)}
 <section className="panel requirements-panel"><div className="section-toolbar"><div className="section-title"><h2>Review requirements</h2><span className="count-pill">{requirements.length}</span></div><div className="table-tools"><label>Show <select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All requirements</option><option value="included">Included</option><option value="excluded">Excluded</option></select></label><label>Sort <select value={sort} onChange={e=>setSort(e.target.value)}><option value="code">Requirement ID</option><option value="source">Source</option></select></label></div></div><p className="muted">Structural extraction keeps testable behavior and filters document titles and narrative. Review wording and source excerpts before confirmation.</p>{selected.length>0&&<div className="selection-bar"><span>{selected.length} selected</span><button className="button secondary" disabled={selected.length<2} onClick={()=>void merge()}>Merge selected</button><button className="text-button" onClick={()=>setSelected([])}>Clear</button></div>}
 {loading?<div className="empty-state compact">Loading requirements…</div>:rows.length?<div className="table-scroll"><table className="data-table"><thead><tr><th scope="col">Select</th><th scope="col">ID / revision</th><th scope="col">Requirement</th><th scope="col">Source</th><th scope="col">Include</th><th scope="col">Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className={!r.included?'excluded-row':''}><td><input type="checkbox" aria-label={`Select ${r.stableCode}`} checked={selected.includes(r.id)} onChange={e=>setSelected(e.target.checked?[...selected,r.id]:selected.filter(v=>v!==r.id))}/></td><td><strong className="code-text">{r.stableCode}</strong><small>Revision {r.revision}</small><span className={`badge ${r.inferred?'badge-amber':''}`}>{r.inferred?'Inferred':r.confidence}</span></td><td className="requirement-text">{editing===r.id?<><label className="sr-only" htmlFor={`edit-${r.id}`}>Requirement text</label><textarea id={`edit-${r.id}`} className="form-control" rows={5} value={editText} onChange={e=>setEditText(e.target.value)}/><div className="inline-actions"><button className="button primary" disabled={!editText.trim()} onClick={()=>void update(r,{text:editText})}>Save revision</button><button className="button secondary" onClick={()=>setEditing(null)}>Cancel</button></div></>:<><span className="badge">{(r.category||'FUNCTIONAL_REQUIREMENT').replaceAll('_',' ')}</span>{r.parentStory&&<small>{r.parentStory}</small>}<div>{r.text}</div></>}</td><td><button className="source-link" onClick={()=>{setExcerpt(r);drawer.current?.showModal();}}>{r.source?.filename||'Source excerpt'}<small>{locator(r.sourceLocator)}</small></button></td><td><input type="checkbox" aria-label={`Include ${r.stableCode}`} checked={r.included} onChange={e=>void update(r,{included:e.target.checked})}/><small>{r.included?'Included':'Excluded'}</small></td><td><div className="row-actions"><button className="text-button" onClick={()=>{setEditing(r.id);setEditText(r.text);}}>Edit</button><button className="text-button" onClick={()=>{setSplit(r);setSplitText(r.text);splitDialog.current?.showModal();}}>Split</button></div></td></tr>)}</tbody></table></div>:<div className="empty-state compact"><Icon name="layers" size={30}/><h3>{requirements.length?'No requirements in this view':'Your requirements will appear here'}</h3><p>Import a source above to begin reviewing source-grounded requirements.</p></div>}</section>
 <section className="panel confirmation-panel"><div><h2>Ready to turn requirements into test cases?</h2><p>Confirm the included requirements to create an immutable snapshot. Later edits create new revisions and leave this snapshot intact.</p></div>{snapshot?<div className="confirmation-success" role="status"><span>✓ Snapshot confirmed · {snapshot.slice(0,10)}</span><Link className="button primary" href={`/projects/${id}/test-cases`}>Continue to generation<Icon name="arrow" size={17}/></Link></div>:<button className="button primary" disabled={confirming||!requirements.some(r=>r.included)||editing!==null} onClick={()=>void confirmRequirements()}>{confirming?'Confirming…':`Confirm ${requirements.filter(r=>r.included).length} requirements`}</button>}</section>
 <dialog aria-label="Requirement source excerpt" className="modal excerpt-drawer" ref={drawer}><div className="modal-heading"><div><div className="eyebrow">SOURCE CONTEXT</div><h2>{excerpt?.stableCode}</h2></div><button className="icon-button" aria-label="Close source excerpt" onClick={()=>drawer.current?.close()}>×</button></div><strong>{excerpt?.source?.filename||'Source document'}</strong><p>{excerpt&&locator(excerpt.sourceLocator)}</p><blockquote>{excerpt?.excerpt||'This requirement is inferred; no original excerpt is available.'}</blockquote><h3>Current requirement</h3><p>{excerpt?.text}</p>{excerpt?.sourceId&&<a className="button secondary" href={`/api/v1/sources/${excerpt.sourceId}/download`}>Download original source</a>}</dialog>
 <dialog aria-label="Split requirement" className="modal" ref={splitDialog}><form onSubmit={doSplit}><div className="modal-heading"><h2>Split {split?.stableCode}</h2><button type="button" className="icon-button" aria-label="Close split requirement" onClick={()=>splitDialog.current?.close()}>×</button></div><p>Separate each new requirement with a blank line. Each item retains the original source reference.</p><label>Requirements<textarea rows={9} value={splitText} onChange={e=>setSplitText(e.target.value)} required/></label>{error&&<p className="error-text" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="button secondary" onClick={()=>splitDialog.current?.close()}>Cancel</button><button className="button primary">Split requirement</button></div></form></dialog></>;
}



