'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useEffect, useState } from 'react';

export function Icon({ name, size = 20 }: { name: string; size?: number }) {
  const paths: Record<string, React.ReactNode> = {
    grid: <><rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/></>,
    settings: <><path d="m9 3-1 3-3 1v4l-2 1 2 2v4l3 1 1 2h5l1-2 3-1v-4l2-2-2-1V7l-3-1-1-3Z"/><circle cx="11.5" cy="12" r="3"/></>,
    plus: <path d="M12 5v14M5 12h14"/>, search: <><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></>,
    arrow: <path d="M5 12h14m-5-5 5 5-5 5"/>, document: <><path d="M14 3H5v18h14V8Z M14 3v5h5M8 12h8M8 16h6"/></>,
    check: <path d="m5 12 4 4L19 6"/>, layers: <><path d="m12 3 9 5-9 5-9-5ZM3 12l9 5 9-5M3 16l9 5 9-5"/></>,
    building:<><path d="M4 21V5l8-3 8 3v16M9 9h1M14 9h1M9 13h1M14 13h1M10 21v-4h4v4"/></>,users:<><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></>,plug:<><path d="m12 22 3-3-3-3M8 2 5 5l3 3M18 8l-2-2-7 7 2 2Z"/><path d="m14 4 2 2M5 16l3 3"/></>,shield:<><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/></>,user:<><circle cx="12" cy="8" r="4"/><path d="M4 22a8 8 0 0 1 16 0"/></>,activity:<><path d="M3 12h4l2-7 4 14 2-7h6"/></>,bell:<><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></>,credit:<><rect x="2" y="5" width="20" height="14" rx="2"/><path d="M2 10h20M6 15h4"/></>,server:<><rect x="3" y="4" width="18" height="6" rx="2"/><rect x="3" y="14" width="18" height="6" rx="2"/><path d="M7 7h.01M7 17h.01"/></>,
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name] || paths.document}</svg>;
}
export function Shell({ children }: { children: React.ReactNode }) {
  const path = usePathname();
  const authPage=['/sign-in','/forgot-password','/reset-password','/verify-email','/mfa','/signed-out','/access-denied','/session-expired'].includes(path);
  const [provider,setProvider]=useState('fixture'),[projectName,setProjectName]=useState(''),[unread,setUnread]=useState(0),[identity,setIdentity]=useState({name:'User',role:'Member'});
  useEffect(()=>{if(authPage)return;fetch('/api/v1/settings').then(r=>r.json()).then(s=>setProvider(s.generator_mode||'fixture')).catch(()=>{});fetch('/api/v1/notifications').then(r=>r.json()).then(n=>setUnread(n.unread||0)).catch(()=>{});fetch('/api/v1/enterprise').then(r=>r.json()).then(d=>setIdentity({name:d.user?.name||'User',role:String(d.role||'Member').replaceAll('_',' ')})).catch(()=>{});const id=path.match(/^\/projects\/([0-9a-f-]{36})/i)?.[1];if(id)fetch(`/api/v1/projects/${id}`).then(r=>r.json()).then(p=>setProjectName((p.project||p).name||'Project')).catch(()=>setProjectName('Project'));else setProjectName('');},[path,authPage]);
  if(authPage)return <div className="auth-shell"><a className="skip-link" href="#main-content">Skip to content</a>{children}</div>;
  return <div className="app-shell"><a className="skip-link" href="#main-content">Skip to content</a><aside className="sidebar">
    <Link className="brand" href="/projects"><span className="brand-mark"><Icon name="layers" size={23}/></span><span>TestPilot<span className="brand-ai"> AI</span></span></Link>
    <Link href="/workspace" className="workspace-switch"><span className="workspace-avatar">TP</span><div><strong>TestPilot Enterprise</strong><small>Demo Workspace</small></div><span className="muted">›</span></Link>
    <div className="nav-label">WORKSPACE</div><nav aria-label="Main navigation"><Link className={`nav-item ${path.startsWith('/projects') ? 'active' : ''}`} href="/projects"><Icon name="grid"/>Projects</Link><Link className={`nav-item ${path === '/workspace' ? 'active' : ''}`} href="/workspace"><Icon name="building"/>Overview</Link><Link className={`nav-item ${path === '/review-queue' ? 'active' : ''}`} href="/review-queue"><Icon name="activity"/>Review queue</Link><Link className={`nav-item ${path === '/search' ? 'active' : ''}`} href="/search"><Icon name="search"/>Global search</Link><Link className={`nav-item ${path === '/notifications' ? 'active' : ''}`} href="/notifications"><Icon name="bell"/>Notifications{unread>0&&<span className="nav-count">{unread}</span>}</Link></nav><div className="nav-label">MANAGE</div><nav aria-label="Workspace management"><Link className={`nav-item ${path === '/team' ? 'active' : ''}`} href="/team"><Icon name="users"/>Team & roles</Link><Link className={`nav-item ${path === '/integrations' ? 'active' : ''}`} href="/integrations"><Icon name="plug"/>Integrations</Link><Link className={`nav-item ${path === '/operations' ? 'active' : ''}`} href="/operations"><Icon name="server"/>Operations</Link><Link className={`nav-item ${path === '/audit' ? 'active' : ''}`} href="/audit"><Icon name="shield"/>Audit trail</Link></nav><div className="nav-label">ADMINISTRATION</div><nav aria-label="Administration"><Link className={`nav-item ${path === '/billing' ? 'active' : ''}`} href="/billing"><Icon name="credit"/>Billing & usage</Link><Link className={`nav-item ${path === '/settings' ? 'active' : ''}`} href="/settings"><Icon name="settings"/>Settings</Link><Link className={`nav-item ${path === '/profile' ? 'active' : ''}`} href="/profile"><Icon name="user"/>Profile & security</Link></nav>
    <div className="sidebar-bottom"><div className="demo-note"><span className="status-dot"/><strong>{provider==='fixture'?'Enterprise sandbox':'Enterprise AI connected'}</strong><p>{provider==='fixture'?'Deterministic mode · source grounded':'Managed model · human approval enforced'}</p></div><div className="user-account"><Link href="/profile" className="user-profile"><span className="avatar">{identity.name.split(/\s+/).map(v=>v[0]).join('').slice(0,2).toUpperCase()}</span><div><strong>{identity.name}</strong><small>{identity.role}</small></div><span>›</span></Link><a className="sidebar-signout" href="/api/auth/logout">Sign out</a></div></div>
  </aside><div className="main-shell"><header className="topbar"><div className="breadcrumb"><span>TestPilot Enterprise</span><span className="breadcrumb-divider">/</span><strong>{projectName||path.split('/').filter(Boolean).at(-1)?.replaceAll('-',' ')||'Workspace'}</strong></div><span className="environment-label enterprise"><span className="status-dot"/>Enterprise workspace</span></header><main id="main-content" className="main-content">{children}</main><footer className="app-footer">Source-grounded quality engineering with governed human review.<span>TestPilot AI · Enterprise</span></footer></div></div>;
}

